### ISSUE TITLE
Allow mpsc senders to be stored in hash sets/maps

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/futures-rs#1177]
I have a use case where I need to store the senders in a hash set, but that is impossible to do directly right now because senders don't implement `Eq + Hash`. I wrote [`same`](https://crates.io/crates/same) crate, so I can workaround it using `Arc`, but it'd be better if I could skip that layer of indirection by putting the senders in the map directly (instead of putting them into `Arc` first).

I'll happily send a PR, but first I want to know which way to take:

* Implement `Eq`, `PartialEq` and `Hash` for senders, on the pointers. Does it make sense though? What "this sender is equal to that one" should mean? Would it be clear from user point of view?
* Implement `Same` and `RefHash` traits from my crate behind a feature flag - this may be more clear to the reader what is being compared/hashed.
* Expose methods `has_same_receiver()` and `channel_hash<H>()` and let the users use them - the methods clearly state what they do and avoid depending on `same`, but increase the burden on users.
* Do nothing - let the users use `Arc<Sender>`. This is inefficient.

What do you think?

**Comment by MajorBreakfast** [comment]
@carllerche @seanmonstar Can you comment on this?

**Comment by Kixunil** [comment]
Ping

**Comment by cramertj** [comment]
`same_receiver` exists now and is public.

**Comment by Kixunil** [comment]
Hmm, that's nice though `Hash` isn't implemented, so it's still impossible to store them in `HashMap`. Could this be reopened, please?

Further, it's only available for 0.3, but I guess it won't be hard to backport (and I might just migrate my code at some point).

**Comment by Kixunil** [comment]
Thanks! Since `same_receiver` is implemented as a method, I figured it's the desired approach (I quite like it too), so made the PR.
