### ISSUE TITLE
Clarify that examples are in async context

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/futures-rs#1203]
As [pointed out on reddit](https://www.reddit.com/r/rust/comments/97dtn3/futures_030alpha3/e49gbll) we don't actually specify anywhere that our examples are in an async context. We could have a comment in the top level docs saying this, but it's likely to be missed. We could have comments in every example, but that's a lot of extra comments. Is there some way we can obviously show this without cluttering the documentation too much? (Also, this was in relation to examples in the blog, those should also be annotated somehow, probably with something louder than the doc examples).

**Comment by Nemo157** [comment]
To explain this a little more, I’m not actually referring to the `task::Context` at all here, by “async context” I mean that we are within an `async fn`/async closure/async block. Maybe a less confusable name would be something like “async scope”?

Basically, all our examples in the documentation have a hidden `block_on(async { ... })` wrapping them since that’s unimportant when you’re using futures from within an `async fn`. This is not immediately obvious to new developers looking at the documentation though, if they try copy-pasting the code into a normal `fn` then it’s likely to fail to compile because `await!` doesn’t work.

**Comment by cramertj** [comment]
I'd be in favor of un-hiding the `async { ... }` wrapping block or the whole thing altogether (including `block_on`), but I don't have particularly strong feelings here. @MajorBreakfast probably has some.

**Comment by dbcfd** [comment]
I think between a concise example, and then documentation that most examples assume an async context, it's probably enough for a start.

I'd definitely prefer all examples to just have an async block around them, in case users don't enter the documentation at the lib.rs level (e.g. google search for and_then)

**Comment by MajorBreakfast** [comment]
Well it would add a bit of boilerplate, but since the question about how to run futures is popping up again and again, I think we should just do it.

**Comment by taiki-e** [comment]
Addressed by #1230
