### ISSUE TITLE
The term "one-shot" is not defined in the documentation.

### ISSUE THREAD

**Issue by jpittis** [rust-lang/futures-rs#1487]
> A one-shot, futures-aware channel

> Creates a new futures-aware, one-shot channel.

It's unclear to me if this means single consumer single producer or if this means you can only send one message on the channel and not two or whether only one message can exist inside the channel at a time.

Seems like this would be a very useful piece of information to add to [the documentation](https://docs.rs/futures/0.1.25/futures/sync/oneshot/index.html).

**Comment by cramertj** [comment]
Yup, I'd be happy to accept a PR clarifying! :)

**Comment by JOE1994** [comment]
I created a PR(#2198) to update the docs regarding this issue. Please take a look! Thank you :cat2:
