### ISSUE TITLE
futures_unordered::IterMut does not implement Send

### ISSUE THREAD

**Issue by canndrew** [rust-lang/futures-rs#1801]
I'm trying to write code that looks like this:

```rust
async fn foo() {
    for future in futures_unordered.iter_mut() {
        do_something_async().await;
    }
}
```

This, unfortunately, makes the future returned by `foo` non-`Send` because the `IterMut` exists across an `await` boundary. Is it possible to fix this and have `IterMut` implement `Send`?

**Comment by cramertj** [comment]
Yes, there's no interesting reason why it isn't `Send`. I suspect it's just "an impl needs to be added" since it contains raw pointers.
