### ISSUE TITLE
Add #[async_test] to futures-test crate?

### ISSUE THREAD

**Issue by ngg** [rust-lang/futures-rs#1890]
Hi!

I'm interested what you're thinking about adding an `#[async_test]` proc-macro to the `futures-test` crate.

There were previous discussions about it at https://github.com/rust-lang-nursery/futures-rs/issues/1169#issuecomment-416301993 and there are also some implementations existing already.

- I have a kind of ugly (sry but I'm not good at proc-macros) but working implementation at [futures-await-test-preview](https://github.com/ngg/futures-await-test/tree/0.3) which uses `futures_executor::LocalPool::new().run_until()`, I'm not sure if this is better or worse then using `block_on`, for my use-cases it seems to work perfectly.
- There is one created for tokio: [tokio-async-await-test](https://docs.rs/tokio-async-await-test/0.1.0/tokio_async_await_test/)

Examples for intended use-case:
```rust
#[async_test]
async fn normal_test() {
    assert!(create_future().await == 4);
}

#[async_test]
#[should_panic]
async fn panic_test() {
    assert!(create_future().await == 5);
}

#[async_test]
async fn result_test() -> Result<(), ()> {
    assert!(create_result_future().await? == 4);
    Ok(())
}
```

Currently I use my implementation to write tests for a Rust wrapper around an asynchronous C++ library, which uses only `futures-0.3`, not `tokio`. I find it really useful, perhaps others would too even if it uses `futures-executor` only at first. Later it could be somehow extended to support other executors as well..

Would you be interested in adding something like this to `futures-test`?

**Comment by LucioFranco** [comment]
@ngg tokio currently has one https://docs.rs/tokio/0.2.0-alpha.5/tokio/attr.test.html
