### ISSUE TITLE
404 in docs

### ISSUE THREAD

**Issue by kpp** [rust-lang/futures-rs#1900]
A lot of links to `src` lead to 404 `File not found`.

- [BufReader](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/io/struct.BufReader.html)   (https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_util/src/futures_util/io/buf_reader.rs.html#37-104)
- [futures/channel/mpsc](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/channel/mpsc/index.html) (https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_channel/src/futures_channel/lib.rs.html#42)
- [futures/task/struct.AtomicWaker](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/task/struct.AtomicWaker.html) (https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_core/src/futures_core/task/__internal/atomic_waker.rs.html#89-92)
- [futures/never/type.Never](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/never/type.Never.html) (https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_util/src/futures_util/never.rs.html#17)
- [futures/stream/struct.AndThen](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/stream/struct.AndThen.html) (https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_util/src/futures_util/try_stream/and_then.rs.html#12-16)
- [futures/stream/trait.Stream](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/stream/trait.Stream.html) (https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_core/src/futures_core/stream.rs.html#27-93)

**Comment by Nemo157** [comment]
This is likely a docs.rs bug since those links are all generated by rustdoc.

**Comment by Nemo157** [comment]
Maybe https://github.com/rust-lang/docs.rs/issues/420

**Comment by jyn514** [comment]
The correct link for BufReader is https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/src/futures_util/io/buf_reader.rs.html#30-35. It looks like rustdoc is appending an extra `futures_util` after the version number.

**Comment by Nemo157** [comment]
This appears to be fixed in the latest docs ([`futures@0.3.1::io::BufReader`](https://docs.rs/futures/0.3.1/futures/io/struct.BufReader.html)) and a local build. Probably simply because we are no longer publishing a `futures-util-preview` package that has a lib named `futures-util` so the `html_root_url` overrides no longer hit https://github.com/rust-lang/docs.rs/issues/298.
