### ISSUE TITLE
Stream combinator to produce non-greedy chunks

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/futures-rs#1919]
The `Chunks` combinator does not yield a next chunk until it is full or the stream ends.

Sometimes, however, it's useful to yield the accumulated items for processing as soon as the upstream polls `Pending`. This might mean that new items won't be available in a while, or that a read buffer from which the items were decoded has been consumed and another OS read is in order, so it would make sense for the application to offer backpressure before attempting to consume that in turn.

**Comment by fisherdarling** [comment]
Hi @cramertj! I'd like to try and tackle this, if that's alright. From what I understand, this would essentially be a modification of the `Chunks` type that returns currently buffered items if the underlying stream returns `Poll::Pending`. Is this correct? What would should the function / type be named?

`ChunksLazy`? `StreamExt::chunks_lazy`

**Comment by mzabaluev** [comment]
This has been addressed since 0.3.5 with the `ready_chunks` combinator.
