### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/futures-rs#1923]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You won't be able to transfer your repository directly, you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by steveklabnik** [comment]
Small wrinkle; [the edition guide](https://github.com/rust-lang-nursery/edition-guide/) points here. As part of this work, after you've moved things, please send a PR to change `src/rust-2018/cargo-and-crates-io/cargo-workspaces-for-multi-package-projects.md` to remove `-nursery`. Thanks!

**Comment by cramertj** [comment]
I'm happy to help with whatever is necessary to keep the project going and under the proper organization.

**Comment by wu-jun-jie** [comment]
what's the state now?  who and when can do this ?
@Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Someone who's "in charge" of this repository needs to confirm the move and then we can move it; I am willing to update the edition guide as part of that.

**Comment by wu-jun-jie** [comment]
@alexcrichton  Sorry to disturb you. I think whether you can do it ?
I think 'futures-rs' is Last few Repo not Move  To 'rust-lang'

**Comment by alexcrichton** [comment]
I've transferred the repository and I've added @cramertj as an admin. I believe ownership/collaborators have otherwise been lost, but @cramertj feel free to add others as you feel is appropriate.

**Comment by Mark-Simulacrum** [comment]
Corrected edition guide link. Closing!
