### ISSUE TITLE
Remove unsafe code by using pin-project-lite crate

### ISSUE THREAD

**Issue by kpp** [rust-lang/futures-rs#1935]
There is so much Pin API related unsafe code can be removed using pin-project or pin-project-lite.
Take a look at a lovely PR by @taiki-e: https://github.com/async-rs/async-std/pull/381

What do you think? I can do that for you if you wish.

**Comment by taiki-e** [comment]
Done in https://github.com/rust-lang/futures-rs/pull/2128
