### ISSUE TITLE
StreamExt::cycle?

### ISSUE THREAD

**Issue by lovesegfault** [rust-lang/futures-rs#1993]
Coming from `Iterator`s I was hoping there would be a way to endlessly loop a `Stream`, like you can `cycle` an `Iterator`; there isn't.

Should such a method exist in `StreamExt`? Is there a way to work around this?

**Comment by lqf96** [comment]
[`async-std`](https://github.com/async-rs/async-std) has [`Stream::cycle`](https://docs.rs/async-std/1.2.0/async_std/stream/trait.Stream.html#method.cycle), and they are compatible because `async-std`'s Stream is simply a reexport of this crate...

**Comment by taiki-e** [comment]
Note that async-std's `StreamExt::cycle` is unsound: https://github.com/async-rs/async-std/pull/903
