### ISSUE TITLE
The example in example/functional doesn't compile

### ISSUE THREAD

**Issue by alfiedotwtf** [rust-lang/futures-rs#1994]
https://github.com/rust-lang/futures-rs/blob/7153ba06eefae260665a5450fa3e95c6b57a74a6/examples/functional/src/main.rs#L3

    error[E0432]: unresolved import `futures::executor::ThreadPool`

**Comment by simeg** [comment]
Add this to your `Cargo.toml`

```
futures = { version = "0.3.1", features = ["thread-pool"] }
```

**Comment by Nemo157** [comment]
Yeah, I just tested building locally after removing the `path` dependency and it worked fine, if you're copying the example into a new project you need to copy the same features from the `Cargo.toml`.

**Comment by alfiedotwtf** [comment]
Ah. Thank you for that :)
