### ISSUE TITLE
Please provide "net" API

### ISSUE THREAD

**Issue by wu-jun-jie** [rust-lang/futures-rs#2018]
when I begin project I choose futures, But then I will use Tokio/async-std instead od futures and no back, because it lack "net" api,  I don't know, why here isn't the  "net" API.

**Comment by leo-lb** [comment]
@wu-jun-jie AFAICT the `futures` crate is not intended to be a full runtime, rather a set of utilities to work with futures.

**Comment by lqf96** [comment]
@wu-jun-jie Rust prefer small, modular crates instead of full-fledged, "battery included" libraries. You can use either `tokio` or `async-std` for asynchronous network programming.

**Comment by wu-jun-jie** [comment]
If like that, who need to use futures? I think tokio/async-std only use Stream form futures, and It will be in std.

**Comment by Pauan** [comment]
@wu-jun-jie There's a lot of useful stuff in `futures`: combinators like `join` / `select`, `FuturesUnordered`, `mpsc::channel` / `oneshot::channel`, `Mutex`, `Sink`, etc.

These are generic utilities which can be used with Futures in general, they aren't for a specific use case (like networking). So they can be useful in *any* project, including with networking.

**Comment by wu-jun-jie** [comment]
Yes, but usually, Tokio/Async-std also has most of this utilities.
