### ISSUE TITLE
Chaining futures which borrow their source.

### ISSUE THREAD

**Issue by vskh** [rust-lang/futures-rs#2027]
I am trying the latest futures and having some struggle.

Most of the methods on sinks and streams follow the pattern of returning custom future type which wraps all necessary information to complete the future. However, some of them don't take ownership of self but instead mutably borrow it.

I'm hitting many examples in websearch with previous futures API version where async methods consumed self and passed it over as argument to next future-generating closure so that one could do chains of and_then() to create a sequence of async operations. However, I don't see how the same could be achieved with mutable borrow kind of methods.

For example, `SinkExt::send_all` wraps mutable borrow of the source sink into `SendAll` future. It means that I can do e.g.:
```
sink.send_all(...).await?;
sink.close().await?;
```
but I can't do
```
sink.send_all(...).then(|_| sink.close()).await?;
```
because of double-borrow. Although, as far as I understand `then` semantics, previous future borrow might be already released by the time the closure passed to `then` is called (is it?).

If I try to wrap sink into arc-mutex combination, I still can't make it work because it's not possible to return future containing lock obtained within closure.

It could probably work if the sink was cloneable but then there would be a need in such clone for every operation I'd want to chain.

Is there a nice and idiomatic way to chain future-returning methods that mutably borrow self into one future?

Thanks!

**Comment by Nemo157** [comment]
Needing to use `then` should be very rare (or even non-existent), you should always be able to replace it with an `async` block and use `await` within that similar to your first example.

If you want to use a chaining style for other reasons, then that should be possible for a third-party library to implement, the same as is necessary to call multiple `&mut` methods in a chain in blocking rust code.

**Comment by vskh** [comment]
Fair suggestion about async block - I totally forgot about it trying to deal with it in C# and alike way!
Thanks, I think that will do.

If anyone else wonders, in the example above that would mean something like this:
```
let compound_future = async {
  sender.send_all(...).await?;
  sender.close().await?;
  Ok(())
};

// do something with `compound_future`, e.g. join!().
```
