### ISSUE TITLE
Incorrect feature for using futures::executor

### ISSUE THREAD

**Issue by Hawk777** [rust-lang/futures-rs#2037]
When I visit [the documentation for futures::executor](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/executor/index.html), I see this text near the top:
> This module is only available when the std feature of this library is activated, and it is activated by default.

This confused me. It is true that all features of `futures_executor` are only available when the `std` feature is enabled on that library. But this is the documentation for `futures::executor`, not `futures_executor`. In that context, I want to know what feature to enable on `futures`, not `futures_executor`, and the correct answer is the `executor` feature, not the `std` feature.

**Comment by taiki-e** [comment]
Looks like that is an old version (perhaps before `executor` feature is introduced). 
[The current version](https://docs.rs/futures/0.3.1/futures/executor/index.html) mentions about `executor` feature.

**Comment by Hawk777** [comment]
You’re right… yet when I click the “API Docs” link on [the website](https://futures.rs/), I get sent to the old version. Perhaps we could repurpose this ticket to figuring out why that’s happening, given that the link appears to point to the “latest” URL fragment?

**Comment by taiki-e** [comment]
Oh, website still using old urls... filed #2040 for fix.
