### ISSUE TITLE
SinkExt::send without flushing

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/futures-rs#2059]
The docs for [SinkExt::send](https://docs.rs/futures/0.3.1/futures/sink/trait.SinkExt.html#method.send) say:
> Note that, because of the flushing requirement, it is usually better to batch together items to send via send_all, rather than flushing between each item.

However, this advice is generally not actionable because `send_all` has such a different interface. Would it not make sense to provide a `send`-like method which doesn't flush the sink? (eg. `give`)

**Comment by Pand9** [comment]
To expand - it's very unclear how to use send_all. I landed here while looking for some instructions on how to use it - and only found out this issue and the other one, that only confirms that send_all is tricky: to use: https://github.com/rust-lang/futures-rs/issues/2024

**Comment by mzabaluev** [comment]
The flushing in `send` and `send_all` means `SinkExt` does not provide an `async`-friendly API for sequential sending of items that could get full performance out of the sink. The only rationale for this that I see is that these are methods designed to be maximally easy to use, and the user of these methods should not get burned with data loss for forgetting to call `.flush()` or `.close()`.

For those of us who would like to write fully performant async code without third-party trait libraries, perhaps there should be sending methods that only feed items to the sink, but don't flush it.
