### ISSUE TITLE
Dropping then locking again prevents other futures from using Mutex

### ISSUE THREAD

**Issue by yankuu** [rust-lang/futures-rs#2071]
When a future drops then reacquires the lock to a Mutex, it can prevent other futures from accessing the Mutex even if they attempt to lock it before the first future's later attempts. In the code ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=75ca6ad5a24b45469583b5105bfb8a48)) below

```
use futures::join;
use futures::lock::Mutex;
use std::{sync::Arc, time::Duration};
// use tokio::sync::Mutex; // prints 0 then 42
use tokio::time;

#[tokio::main]
async fn main() {
    let state1 = Arc::new(Mutex::new(0));
    let state2 = state1.clone();

    join!(display(state1), change(state2));
    // join!(change(state2), display(state1)); // always prints 42
}

async fn display(state: Arc<Mutex<usize>>) {
    for _ in 0..3 {
        // Immediately awaits to lock after dropping from previous interation
        let state = state.lock().await;
        println!("State: {}", *state);

        // Other futures that attempt to acquire the lock will fail
        time::delay_for(Duration::from_secs(1)).await;

        // Lock dropped here
    }
}

async fn change(state: Arc<Mutex<usize>>) {
    *state.lock().await = 42;
}
```

The `change` future never gets to change the state because the `display` future still holds the lock while delaying. After `display` drops the lock at the end of the loop body, it again becomes the first future to lock the Mutex in the next iteration.

I think this behavior is confusing. Intuitively, since the long-running `display` future has repeatedly given up the lock, it is natural to assume that other futures get ample opportunities to use the Mutex. This is also what `tokio::sync::Mutex` does. But in this case, a long-running future checking the state of a Mutex like the `display` future here could accidentally block other futures that await the Mutex for their use.

**Comment by yankuu** [comment]
This is somewhat similar to #1663, but in their case the future holding the lock does not repeatedly drop it.

**Comment by Matthias247** [comment]
This isn't purely about the `Mutex`. Your `display` task also acquires the lock again before the other task ever gets to run. If you want to give other tasks a chance to run you need to yield back to the executor. 

A "fair" `Mutex` which keeps a queue of blocked tasks and doesn't let other tasks jump in would also solve the issue. But the futurers-rs version is deliberatily not designed that way. There however exist other async Mutex implementations in the ecosystem which are fair (e.g. the one in futures-intrusive).

**Comment by yankuu** [comment]
I am genuinely surprised! A major benefit of `Mutex` is that users don't need to remember to release the lock. As the Rust [Book](https://doc.rust-lang.org/book/ch16-03-shared-state.html#the-api-of-mutext) put it:

"The `MutexGard` smart pointer ... releases the lock automatically ... As a result, we don’t risk forgetting to release the lock and blocking the mutex from being used by other threads because the lock release happens automatically."

But now the user needs to remember to yield back to the executor in order not to block other threads. I think this requirement is a little inconsistent in spirit with the general Rust concurrency story, and might be worth putting into documentation.

Thank you very much for your clarification! So no code change is needed here. I'll close the issue shortly. Just remember to yield back.
