### ISSUE TITLE
Broken link in docs to channel::mpsc::TrySendError

### ISSUE THREAD

**Issue by kpp** [rust-lang/futures-rs#2072]
https://github.com/rust-lang/futures-rs/blob/771513cea996bac0c8c4017be687e289c966f504/futures-channel/src/mpsc/mod.rs#L161

https://docs.rs/futures/0.3.4/futures/channel/mpsc/struct.TrySendError.html  see `try_send` link to url://sender::try_send

**Comment by taiki-e** [comment]
related: #1903

**Comment by kpp** [comment]
Closing as a duplicate. Thanks for pointing this out.
