### ISSUE TITLE
Possibly over-aggressive dependency changes due to release process/workspace use.

### ISSUE THREAD

**Issue by kentfredric** [rust-lang/futures-rs#2084]
I'm spotting some odd behaviour, and I suspect its due to the workspace-oriented release flow.

For example comparing `futures-sink 0.3.1` with `futures-sink 0.3.4` yields no obvious changes to me that would explain why `futures-channel 0.3.4` would require it, as opposed to `futures-channel 0.3.1`.

There's metadata changes, but they look cosmetic.

Ideally, dependencies should declare upgrades only out of necessity, and let cargo and other build chains decide when they need to upgrade a dependency.

But as it stands, it looks to be creating a bunch of "busywork" for downstream to replicate, without a tangible benefit.

I don't oppose publishing releases to fix cosmetic metadata changes, just having newer releases of other things *require* those changes produces more problems for the consumer side than I think is worth it.

**Comment by cramertj** [comment]
Previously, `futures-sink` required `futures-channel`. That was changed to work the other way around, and instead use feature flags to disable the integration.
