### ISSUE TITLE
noop_waker_ref is unsound

### ISSUE THREAD

**Issue by goffrie** [rust-lang/futures-rs#2091]
[Demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=54ee9d6853898ff55932faa419efbbf2) which segfaults in playground:
```rust
use futures::task::noop_waker_ref;
fn main() {
    let waker = std::thread::spawn(|| noop_waker_ref()).join().unwrap();
    waker.wake_by_ref();
}
```

`noop_waker_ref()` returns a `'static` reference into TLS, but `Waker` is `Sync` so `&'static Waker` is `Send`, allowing the reference to outlive the thread it came from.

It should use something more like a lazy_static.

**Comment by Nemo157** [comment]
@goffrie thanks, opened #2095 which should fix this.
