### ISSUE TITLE
Cannot use macros when crate is renamed

### ISSUE THREAD

**Issue by That3Percent** [rust-lang/futures-rs#2099]
When the `futures` crate is renamed:
```toml
futures03 = { version = "0.3.1", package = "futures" }
```

Macros like `try_join` cannot find the crate.
Eg:
```rust
async fn test() {
    futures03::try_join!()
}
```

fails with
```
failed to resolve: could not find `futures` in `{{root}}`
```

This impedes migration from version 0.1 to version 0.3, since one of the two futures crates must be renamed.

**Comment by cramertj** [comment]
This is known, but in general there's no way to solve this for procedural macros (at least that I know of). @dtolnay may know if there have been any recent innovations here?

**Comment by That3Percent** [comment]
@cramertj This crate claims to solve this problem, but I have not tried it myself - [https://crates.io/crates/proc-macro-crate](proc-macro-crate)

**Comment by dtolnay** [comment]
I definitely do not recommend using proc-macro-crate. It's based on parsing a Cargo.toml at macro expansion time so it breaks non-Cargo builds.

I think this is possible to make work correctly but I don't know if anyone has done it yet. Conceivably the `try_join!` macro invoked by the user could be a macro_rules macro that passes a $crate token to an underlying procedural macro.

**Comment by cramertj** [comment]
@dtolnay I believe I tried that in the past and found that `$crate` passed to a procedural macro didn't resolve correctly. Could be worth trying again, though, as I don't remember precisely.

**Comment by taiki-e** [comment]
> Conceivably the `try_join!` macro invoked by the user could be a macro_rules macro that passes a $crate token to an underlying procedural macro.

I think this works, but I find a way to support not only rename but also reexport, so I filed #2124.
