### ISSUE TITLE
are there any plans to move AsyncRead and others into std library

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/futures-rs#2105]
`tokio` has his `AsyncRead` trait and others, `async-std` use `futures` trait and re-export it.

I notice https://github.com/tokio-rs/tokio/pull/1744 says

> Once AsyncRead / AsyncWrite are added to std, Tokio will provide
> implementations for its types.

I wonder if `futures`'s `AsyncRead` and others will move into std library?

**Comment by yoshuawuyts** [comment]
@Sherlock-Holo there's no agreed timeline or proposal for this, but there seems to be a general consensus that this is desirable. Conversations of what to tackle next in the async space have been ongoing and documented on [Niko's blog](http://smallcultfollowing.com/babysteps/). In particular the following two interviews seem worth checking out:

- [#5 Steven Fackler](http://smallcultfollowing.com/babysteps/blog/2020/01/20/async-interview-5-steven-fackler/) covers challenges and directions around async `Read`/`Write` and uninitialized memory. This shares a perspective grounded in the Tokio ecosystem.
- [#7 Withoutboats](http://smallcultfollowing.com/babysteps/blog/2020/03/10/async-interview-7-withoutboats/#extending-the-stdlib-with-some-key-traits) shares a high-level lang/libs team perspective on which steps to prioritize next to progress the state of async Rust.

In the end it's up to the lang and libs teams to prioritize what to pick up next. I'm not aware of any concrete _plans_, but the intention seems to be clear that this is indeed something that people would like to see happen.

**Comment by taiki-e** [comment]
Closing in favor of https://github.com/rust-lang/wg-async-foundations/issues/23
