### ISSUE TITLE
Release 0.3.2 should be 0.4.0

### ISSUE THREAD

**Issue by jsancio** [rust-lang/futures-rs#2115]
I believe that when PR https://github.com/rust-lang/futures-rs/pull/2049 was merged and release it should be consider a breaking change since it changed the semantic of `FutureUnordered::poll_next`.

This is cargo's version [semantic](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements):
> This compatibility convention is different from SemVer in the way it treats versions before 1.0.0. While SemVer says there is no compatibility before 1.0.0, Cargo considers 0.x.y to be compatible with 0.x.z, where y ≥ z and x > 0.

I think this means that release 0.3.2 should have really been versioned as 0.4.0.

It is probably already too late to do anything.

**Comment by jonhoo** [comment]
I don't think it is a breaking change, since `FuturesUnordered` still follows the contract of `Future::poll`. Does my answer in https://github.com/rust-lang/futures-rs/pull/2049#issuecomment-609101561 help, or is there some other breakage you are thinking of?

**Comment by jsancio** [comment]
Agree, not a breaking change based on the comments above.
