### ISSUE TITLE
Bug in Chain-based future's implementations of FusedFuture

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/futures-rs#2118]
https://github.com/rust-lang/futures-rs/blob/2f8943da9a0fcef208e86ae2f0f0152191629dcc/futures-util/src/future/future/chain.rs#L48

As you can see, once the second future returns ready it will return immediately without first transitioning to the `Empty` state, which is what the `is_terminated` function looks at:

https://github.com/rust-lang/futures-rs/blob/2f8943da9a0fcef208e86ae2f0f0152191629dcc/futures-util/src/future/future/chain.rs#L16-L18

**Comment by taiki-e** [comment]
I think this is fixed in #2128.

**Comment by Diggsey** [comment]
Yep.
