### ISSUE TITLE
async equivalent of std::io::LineWriter?

### ISSUE THREAD

**Issue by anp** [rust-lang/futures-rs#2131]
`AsyncBufReadExt::lines` exists but there's no async+line-buffered generic writer available AFAICT.

In scope?

**Comment by taiki-e** [comment]
I would accept a PR to add this. (I've previously tried this a bit, but I remember finding it difficult.)

**Comment by FelipeLema** [comment]
hi, there

I was trying to address this by adapting [`std::io::LineWriter`](https://doc.rust-lang.org/src/std/io/buffered/linewriter.rs.html) and its [`LineWriterShime`](https://doc.rust-lang.org/src/std/io/buffered/linewritershim.rs.html) sidekick, but I'm having trouble handling `Pin`s and references.

Particularly, I'm not understanding how a WIP-`futures_util::io::LineWriterShim` can receive WIP-`futures_util::io::LineWriter` 's buffer writer.

If, instead, I try to merge `LineWriterShim` into `LineWriter`, then I have trouble with newly-added-`BufWriter::write_to_buffer_unchecked()`

Perhaps I should d a draft PR instead 🤔

**Comment by FelipeLema** [comment]
let me re-phrase the above

I'm not certain of how to "balance out" refs and pinning.

For doing behavioural stuff, all is present in `std::io::LineWriter`, but it's all doing mutable refs (specifically, writing directly to `BufWriter`'s internal buffer). For doing async stuff, all is done with `Pin::new`, `#[pin]` and such.

Both pin-ey and ref-ey code don't play well with each other.

For example, how would I write a `poll_write` that may write to a `BufWriter`'s internal buffer? Right now, rustc is complaining that I cannot declare [`flush_if_completed_line()`](https://doc.rust-lang.org/src/std/io/buffered/linewritershim.rs.html#44-49) to receive `self` as  `Pin<&mut Self` or as `&mut Self`

**Comment by taiki-e** [comment]
> For example, how would I write a `poll_write` that may write to a `BufWriter`'s internal buffer? Right now, rustc is complaining that I cannot declare [`flush_if_completed_line()`](https://doc.rust-lang.org/src/std/io/buffered/linewritershim.rs.html#44-49) to receive `self` as `Pin<&mut Self` or as `&mut Self` (not with the same error, of course)

In #2477, you need to always use `Pin<&mut Self>` instead of `&mut self`.
