### ISSUE TITLE
Add normal `read()` / `peek()` async functions to `AsyncBufReadExt`

### ISSUE THREAD

**Issue by sdroege** [rust-lang/futures-rs#2144]
This would fill the internal buffer until the given amount is reached and then provide access to it. `read()` could return a value that implements `Deref<Target=[u8]>` and on `Drop` consumes the read data, `peek()` would only provide direct access to an `&[u8]`.

This seems useful to have to allow copy-less operation on `AsyncBufRead` impls. If they implement `AsyncRead` in addition, a copy would always be necessary.

Inspired partially by https://boats.gitlab.io/blog/post/io-uring/

**Comment by Nemo157** [comment]
What is a buffered reader to do if the requested amount exceeds the internal buffer size?

**Comment by sdroege** [comment]
Return less, just like `AsyncRead::read()` can return less

**Comment by Nemo157** [comment]
So this could purely be an `AsyncBufReadExt` sugar around `poll_fill_buf` + `consume`, not something implemented for each `AsyncBufRead`?

`peek` seems like it would just be the missing `AsyncBufReadExt::fill_buf` (which IIRC [might have lifetime issues](https://github.com/rust-lang/futures-rs/pull/2021#issuecomment-570774003)).

**Comment by sdroege** [comment]
Yes that is exactly what I meant, sorry for not being more clear :)

**Comment by taiki-e** [comment]
I think this is addressed by #2225.
