### ISSUE TITLE
mpsc::channel async receive

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/futures-rs#2153]
Is it possible to use `await` with `mpsc::channel` ?  For example, something like:
```
let (tx, rx) = mpsc::channel(100);
<snip>
let data = rx.recv().await;
```
It seems that there is no such `recv()` available for `Receiver`.  What's the recommended method/pattern to receive from the channel asynchronously?

**Comment by Pauan** [comment]
@keepsimple1 The `Receiver` is a `Stream`, so you would use the [`StreamExt`](https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html) methods, such as [`for_each`](https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.for_each):

```rust
rx.for_each(|data| {
    // ...
}).await;
```

Or if you only want to wait for one element you would use [`next`](https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.next):

```rust
if let Some(data) = rx.next().await {
    // ...
}
```

But if you only want one element then you're better off using [`oneshot`](https://docs.rs/futures/0.3.5/futures/channel/oneshot/fn.channel.html).

**Comment by keepsimple1** [comment]
thanks @Pauan ! It will be useful to include such info/example in the online docs of [`mpsc`](https://docs.rs/futures/0.3.5/futures/channel/mpsc/index.html) .

**Comment by heckad** [comment]
Maybe add recv for more compatibility with channels from Tokio?

**Comment by keepsimple1** [comment]
Now I have better understanding about async stuff, and using [`async-channel`](https://crates.io/crates/async-channel) crate. It works pretty well.
