### ISSUE TITLE
future::select example

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/futures-rs#2163]
I felt the current example in `future::select` documentation is too advanced / complicated for a new user. I think that whoever trying to read this example is likely a new user.

https://github.com/rust-lang/futures-rs/blob/95d5801c0d95e9c9c07b96b74ec3ecb3a269585f/futures-util/src/future/select.rs#L31-L45

Is it possible to have a simpler / more basic example for this function? Particularly, it will be great if the example can clearly show what the value(s) returned in each arm are.

**Comment by johnmarkwayve** [comment]
I'd also love an example that is:

1. more explicit about what the elements of the pairs within the `Either` are, you have to do a lot of parsing of this example to tell what `x`, `a`, `y`, and `b` are meant to mean

2. uses this function in a more realistic scenario than reimplementing something `select` doesn't do

**Comment by taiki-e** [comment]
Done in #2182
