### ISSUE TITLE
how to use with reqwest?

### ISSUE THREAD

**Issue by JsBlueCat** [rust-lang/futures-rs#2164]
i want to write this function 
``` rust
 pub async fn get_mining_info(&self) -> impl Future<Output = Result<MiningInfoResponse, FetchError>> {
        reqwest::get(self.uri_for("burst"))
            .headers((*self.headers).clone())
            .query(&GetMiningInfoRequest {
                request_type: &"getMiningInfo",
            })
            .send()
            .await?
            .json::<HashMap<String, String>>()
            .await?;
}
```
how to get the Future since you have update from 0.1 to 0.3

**Comment by Nemo157** [comment]
`reqwest` 0.10 is using `std::future::Future`, the same as `futures` 0.3, so they should be fully compatible with each other and `async fn`. If you are stuck on `reqwest` 0.9 you can take a look at the [`futures::compat`](https://docs.rs/futures/0.3.5/futures/compat/index.html) module for adaptors that allow converting `futures@0.1::future::Future`s to `std::future::Future`s.
