### ISSUE TITLE
`try_join_all` behavior does not seem to match the docs

### ISSUE THREAD

**Issue by Gastove** [rust-lang/futures-rs#2167]
Working with `try_join_all`, it appears that the return type does not match the docs. 

What I'm doing: I'm generating batches of queries to run against a database. The database uses `tokio` under the hood, so the `tokio` runtime is already defined and required. Thus, I spawn a task for each query using `tokio::spawn`, getting back a `JoinHandle` for each. I hand the resulting iterable to `try_join_all`. In practice, this looks a lot like: 

```rust
let queries = generator.clone().take(10);
let the_work = queries    
    .map(|q| {
        let pool = self.pool.clone();
        Worker::new(q, pool)
    })
    .map(|worker| tokio::spawn(async {
        worker.work().await?;
        Ok::<(), QueryExecError>(())
    }));

// At this point, the_work has this type:
// Map<Map<Take<Generator>, |Query| -> Worker>, |Worker| -> JoinHandle<Future::Output<Result<(), QueryExecError>>>>
match futures::future::try_join_all(the_work).await {
    Ok(o) => Ok(format!{"Got {:?}", o}),
    Err(e) => Err(e),
}
```

The type of `the_work` appears correct to me. But, when I execute the code, I get this output:
```
Got [Ok(()), Ok(()), Err(...), Err(...), Ok(()), Ok(()), Err(...), Ok(()), Ok(()), Err(...)]
```
All the OKs and Errs are there, but I appear to be getting an `Ok<Vec<Result>`. 

Is this outcome expected?

Thanks for the excellent libraries and the time!

**Comment by Gastove** [comment]
AHA. `JoinHandle` has it's own result type, which the docs helpfully elide. `try_join_all` is working perfectly well, there's just an extra layer in the way. For anyone who might wander across this, if you dig in to the [Tokio Docs for JoinHandle](https://docs.rs/tokio/0.2.21/tokio/task/struct.JoinHandle.html), the result type is inside two different collapsed-by-default menus under the description of the implementation of the `Future` trait for `JoinHandle<T>`.

**Comment by webern** [comment]
Hello from the future. I am having this same problem and your aha moment isn't helping me. I am also getting a `Vec<Result<Whatever>>` but all examples I can find by scouring the internet imply that I should get a `Vec<Whatever>>`.
