### ISSUE TITLE
`StreamExt::scan` is barely useful due to lifetime issue

### ISSUE THREAD

**Issue by jerry73204** [rust-lang/futures-rs#2171]
Continuing #2046, the lifetime issue is still a headache, that the async block basically cannot access the state when it's executed. Currently, I stick to `futures::stream::unfold` workaround to bind streams with states.. IMO, the future block of `scan` could own the state and returns to stream just like what `unfold` did . Perhaps we can make this change, or are there any other considerations for this design?

**Comment by ivormetcalf** [comment]
I just ran into this problem and wholeheartedly agree. Something like:

`
fn scan<S, B, Fut, F>(self, initial_state: S, f: F) -> Scan<Self, S, Fut, F>
where
    F: FnMut(S, Self::Item) -> Fut,
    Fut: Future<Output = Option<(B, S)>>, 
`

might perhaps be a better design.

**Comment by jerry73204** [comment]
@ivormetcalf you can use [code block quote](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) for better readability.

**Comment by hjfreyer** [comment]
Does anyone know of a library that implements @ivormetcalf 's proposed signature?
