### ISSUE TITLE
Add a wrapper around ReadHalf which does delegate AsyncBufRead

### ISSUE THREAD

**Issue by zserik** [rust-lang/futures-rs#2172]
Currently, `ReadHalf` doesn't implement `AsyncBufRead`, only `AsyncRead`, but I think that
```rust
impl<X: AsyncBufRead> AsyncBufRead for ReadHalf<X>
```
should be possible/implementable. Is there any argument against this / why this wouldn't work?

**Comment by Nemo157** [comment]
Seems like a very good idea to me.

**Comment by zserik** [comment]
ok, I just found out which makes that so difficult: The `consume` method has no `Context` argument, thus, we have no easy way to acquire the lock.

**Comment by zserik** [comment]
We could delay the call to the `consume` method conditionally (because we don't want to have a `AsyncBufRead` bound on the `AsyncRead` impl) using a helper trait, but that would require specialization, I think...

**Comment by zserik** [comment]
As this would either require `feature(min_specialization)` or a change to the `trait AsyncBufRead` (change `consume` to `poll_consume` with a `cx` arg), this won't fix soon, but if one needs that, it is possible to build a custom work-around using `BiLock`, just use `locking` on a more coarse level, e.g. outside of both `poll_fill_buf` and `consume`, in the surrounding scope, such that both are called under the same lock. `--> EWONTFIX`

**Comment by zserik** [comment]
It may be possible to fix this by introducing a new type `BufReadHalf`, which is constructable from `ReadHalf`, but only if the inner type support `AsyncBufRead`, and could include this optimization.

**Comment by zserik** [comment]
As stated in https://github.com/stjepang/async-dup/issues/1, this probably won't work.
