### ISSUE TITLE
Add some kind of utility function to automatically unlock a BiLock when yielding

### ISSUE THREAD

**Issue by zserik** [rust-lang/futures-rs#2174]
previous issue: #2172

Currently, I work around issue #2172 using a custom `ReadLine` implementation, which does lock a `BiLock` to access the inner `poll_*` methods, but I think that this pattern could be abstracted, to be able to wait for some async function, while the object it depends on is behind a `BiLock`, without needing to hold the lock the whole time while waiting for some resource to become available (e.g. some kind of "poll_with" helper function, which gets some kind of `FnMut` as argument, but I wasn't able to come up with an easy and clean solution...).
example: https://github.com/YZITE/encsess2/blob/master/demo-zsittle/src/bin/yzesd2-server.rs#L58-L75

**Comment by taiki-e** [comment]
> example: https://github.com/YZITE/encsess2/blob/master/demo-zsittle/src/bin/yzesd2-server.rs#L58-L75

This link seems invalid now
