### ISSUE TITLE
Why is there no `FusedStream` implementation for `FuturesOrdered`?

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/futures-rs#2192]
While `FuturesUnordered` has a [`FusedStream` implementation](https://docs.rs/futures/0.3.5/futures/stream/struct.FuturesUnordered.html#impl-FusedStream), the `FuturesOrdered` type does not. Is there any reason for this missing implementation or is this just an oversight?

**Comment by taiki-e** [comment]
I think this is an oversight. (Basically, any stream that can see that itself is empty can implement `FusedStream`).

**Comment by phil-opp** [comment]
Good to hear that. A `FusedStream` implementation would make it much easier to work with `FuturesOrdered` in a `select` block. (You can't use the `fuse()` method when you're adding futures to the set later.) 

Would a simple check for `FuturesOrdered::len() == 0` suffice for a `FusedStream` implementation? If so, I'll be happy to send in a PR for this.

**Comment by taiki-e** [comment]
> Would a simple check for `FuturesOrdered::len() == 0` suffice for a `FusedStream` implementation?

I think the correct implementation is `self.in_progress_queue.is_terminated() && self.queued_outputs.is_empty()`.

---

> (Basically, any stream that can see that itself is empty can implement `FusedStream`).

This (my comment) is not correct (sorry!). 
If I understand correctly, it's probably actually something like:
* Even if it is empty, if it may return `Ready(Some)` in the future, it should be considered as "terminated" only after `Ready(None)` is returned once. (e.g., [`FuturesUnordered`](https://github.com/rust-lang/futures-rs/blob/19831dbecd13961fbd4243c1114663e24299c33d/futures-util/src/stream/futures_unordered/mod.rs#L429-L433) that elements may be added)
  ([However, `FusedStream` implementations may be provided that considers `is_empty` as `is_terminated` for specific use cases](https://github.com/rust-lang/futures-rs/pull/1259#discussion_r217122532))
* If there is no possibility of returning `Ready(Some)` in the future, it can be considered as "terminated" regardless of whether `Ready(None)` was returned once. (e.g., `stream::once`, `stream::empty`, `stream::pending`, `StreamExt::take`)

(cc @cramertj: my understanding is correct?)
