### ISSUE TITLE
Stream. Could not to Collect from Iter of Result<_, _> into Result<Vec<_>, _>

### ISSUE THREAD

**Issue by Mnwa** [rust-lang/futures-rs#2193]
Hey team! I really like this library and use it, everyone, where I use async Rust! But, it's problem makes me sad :( 
With iterators, I can do this convert, but with streams, I must first collect a stream to `Vec<Result<_, _>>` and after that use `into_iter().collect::<Result<Vec<_>, _>>`. Maybe you'll add support for these converts?

**Comment by Nemo157** [comment]
You can use `TryStreamExt::collect` for better integration with `Stream<Item = Result<_, _>>`.

**Comment by Mnwa** [comment]
Lol. I don't find that. Thanks!
