### ISSUE TITLE
select!{} documentation has truncated paragraph

### ISSUE THREAD

**Issue by Moongoodgirl** [rust-lang/futures-rs#2194]
The second paragraph of the `select!{}` docs reads,

> If an expression which yields a `Future` is passed to `select!` (e.g. an `async fn` call) instead of a `Future` by name the `Unpin` requirement is relaxed, since the macro will pin the resulting `Future` on the stack. However the `Future` returned by the expression must still implement `FusedFuture`. **This difference is presented**

(emphasis mine)

It is not clear how the difference is presented. It seems that this paragraph has been accidentally truncated.

**Comment by taiki-e** [comment]
@Matthias247: This seems added in #1874. Do you remember what you were trying to write here? If not, I think it's okay to just delete it.

**Comment by Matthias247** [comment]
This was probably just my brain which sometimes shows data loss when doing many context switches while writing long docs 😀. Those have to be better reviewed.

Feel free to delete the incomplete sentence. I don't know anymore what it was about.
