### ISSUE TITLE
A stream wrapper that holds the latest value exists?

### ISSUE THREAD

**Issue by akiradeveloper** [rust-lang/futures-rs#2199]
I am trying to solve a problem like this:

1. I have a stream of T (let's call this S) that yields every 1 sec. It is basically like repeat stream of T but with some interval. 
2. I want a stream wrapper around S so it returns None if S hasn't yield anything yet, Some(latest value) otherwise.

I handmade this wrapper by myself but with some combination of the existing stream wrappers could I solve my problem?

```rust
#[pin_project]
pub struct CachedStream<St: Stream> {
    #[pin]
    stream: St,
    cached: Option<St::Item>,
}
impl<St: Stream> CachedStream<St> {
    pub fn new(s: St) -> Self {
        Self {
            stream: s,
            cached: None,
        }
    }
}
impl<St: Stream> Stream for CachedStream<St>
where
    St::Item: Clone + std::fmt::Debug,
{
    type Item = St::Item;
    #[project]
    fn poll_next(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Option<Self::Item>> {
        #[project]
        let CachedStream { mut stream, cached } = self.project();
        loop {
            let item = stream.as_mut().poll_next(cx);
            // dbg!(&item);
            match item {
                Poll::Ready(Some(x)) => {
                    cached.replace(x);
                }
                Poll::Ready(None) => {
                    return Poll::Ready(None);
                }
                Poll::Pending => {
                    if cached.is_some() {
                        break;
                    } else {
                        return Poll::Pending;
                    }
                }
            }
        }
        Poll::Ready(cached.clone())
    }
}
```

**Comment by taiki-e** [comment]
I don't think there is a combinator or combinator combination that provides equivalent functionality. (Maybe you could do something similar using ready_chunks, but probably very inefficient.)

**Comment by akiradeveloper** [comment]
Thanks. it seems to be yes.

> If the underlying stream ended and only a partial vector was created, it'll be returned. Additionally if an error happens from the underlying stream then the currently buffered items will be yielded.

Finally, I realize what I am looking for a variant of tokio::sync::watch that **won't** delete the retained value after polled. Now I am doing my work with wrapping the sync::watch's receiver by the above `CachedStream` but yes I feel better if there is one like this in the official.

**Comment by taiki-e** [comment]
> Finally, I realize what I am looking for a variant of tokio::sync::watch that **won't** delete the retained value after polled. Now I am doing my work with wrapping the sync::watch's receiver by the above `CachedStream` but yes I feel better if there is one like this in the official.

IIUC, `tokio::sync::watch::Receiver` doesn't delete the latest value until the next `recv` or `next` call, so it should be able to use the [`borrow`](https://docs.rs/tokio/0.2.22/tokio/sync/watch/struct.Receiver.html#method.borrow) method to get the latest value.

**Comment by akiradeveloper** [comment]
I didn't know that. Thank you for the information. I will check later and get back to you

**Comment by akiradeveloper** [comment]
@taiki-e I tried this using async_stream macro but this is not what I what because the code looks like generating a producer that infinitely looping in maximum speed with which the AsyncStream is the consumer.

```rust
    let st = async_stream::stream! {
        loop {
            yield rx.borrow().clone();
        }
    };
```

Unfortunately, what I want is a stream that borrows and yields only once when the client code polls. So this will become something like

```rust
let st = async_stream::on_poll! {
    yield rx.borrow().clone();
}
```

I don't want to handcraft classes to do this. Do you have some idea of existing tools to make this happen?

**Comment by akiradeveloper** [comment]
I tried this. `it` is infinite lazy list of borrowed values and the for loop in the stream macro is taking this values one by one. This is probably what I want.

```rust
    let it = std::iter::repeat_with(|| {
        rx.borrow().clone()
    });
    let st = async_stream::stream! {
        for x in it.into_iter() {
            yield x
        }
    };
```

**Comment by taiki-e** [comment]
@akiradeveloper 
`borrow` does not update the value, so it needs to be used in combination with `recv`/`next`/`poll_next`. Instead of using `async_stream!`, you probably need to wrap the receiver with a helper function something like:

```rust
use futures::stream::{self, Stream, StreamExt};
use std::task::Poll;
use tokio::sync::watch;

fn watch_helper<T: Clone>(mut rx: watch::Receiver<T>) -> impl Stream<Item = T> {
    stream::poll_fn(move |cx| {
        while rx.poll_next_unpin(cx).is_ready() {}
        Poll::Ready(Some(rx.borrow().clone()))
    })
}

```

**Comment by akiradeveloper** [comment]
@taiki-e My problem is resolved. Thank you so much!
