### ISSUE TITLE
Shall quadratic complexity of `join_all` be documented?

### ISSUE THREAD

**Issue by vi** [rust-lang/futures-rs#2201]
* https://github.com/tokio-rs/tokio/issues/2401
* https://users.rust-lang.org/t/hyper-tonic-client-performance/47253/2

**Comment by Nemo157** [comment]
Maybe even a

```
#[cfg(debug_assertions)]
if futures.len() > 1000 {
  warn!("join_all is only intended for running small dynamic lists of futures, use FuturesUnordered for large numbers");
}
```

**Comment by vi** [comment]
Does `futures` really use `log`?

**Comment by Nemo157** [comment]
Not currently, but the only other option I can think of would be `debug_assert!` which seems far too drastic to me.

**Comment by taiki-e** [comment]
(I think the underlying solution is to change the name to include a word that describes its feature(=only efficient for relatively small lists), but that's a breaking change of course.)

**Comment by Darksonn** [comment]
Another option would be to have it use `FuturesUnordered` internally when the number of futures is large.

**Comment by EFanZh** [comment]
Does `try_join_all` and `select_all` suffer from the same issue?

**Comment by Darksonn** [comment]
Yes. For `try_join_all` it is exactly the same. For `futures::future::select_all`, it's a bit harder to hit, but it's still there. (Note that `futures::stream::select_all` is a different story.)

**Comment by taiki-e** [comment]
#2412 is published in 0.3.17

**Comment by mox692** [comment]
I may be missing something, but is there a reason we are using `FuturesOrdered` instead of `FuturesUnordered`?

**Comment by Xuanwo** [comment]
> I may be missing something, but is there a reason we are using `FuturesOrdered` instead of `FuturesUnordered`?

The order in which future results are returned is important.
