### ISSUE TITLE
Rust 1.46.0 - type-length limit while instantiating future::Ready

### ISSUE THREAD

**Issue by dessalines** [rust-lang/futures-rs#2202]
I'm getting this error on `futures-util` since upgrading to rust 1.46.0 : 

```
error: reached the type-length limit while instantiating `<futures::future::Ready<std::res...y>::new_service::{{closure}}#0]>`
   --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/mod.rs:142:5
    |
142 | /     fn map<U, F>(self, f: F) -> Map<Self, F>
143 | |     where
144 | |         F: FnOnce(Self::Output) -> U,
145 | |         Self: Sized,
146 | |     {
147 | |         assert_future::<U, _>(Map::new(self, f))
148 | |     }
    | |_____^
    |
    = note: consider adding a `#![type_length_limit="1471465"]` attribute to your crate

error: aborting due to previous error
```

**Comment by taiki-e** [comment]
Can you provide code that could reproduce this problem? I can't reproduce this, but in any case, if you can compile with the previous version of rustc, I think this is not a problem on futures-rs side, but a regression of rustc.

possibly related: https://github.com/rust-lang/rust/issues/75992, https://github.com/rust-lang/rust/issues/72408

**Comment by dessalines** [comment]
I'll close in that case, yes it does compile with previous versions of rustc. Its project with a large codebase, [lemmy](https://github.com/lemmynet/lemmy), so I don't know how to replicate it outside of that.
