### ISSUE TITLE
Bug in impl FusedFuture for futures::future::Map

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/futures-rs#2213]
It doesn't correctly propagate the termination of the underlying future

```rust
use futures::future::FusedFuture;
use futures::future::FutureExt;

fn main() {
    assert!(futures::future::pending::<()>().is_terminated());
    assert!(futures::future::pending::<()>().map(|()| ()).is_terminated());
}
```

```console
> cargo run
thread 'main' panicked at 'assertion failed: futures::future::pending::<()>().map(|()| ()).is_terminated()', src/main.rs:6:5
```

This should be delegating through to the inner future:

https://github.com/rust-lang/futures-rs/blob/32d970edd7281908cd4af05915bdc9136eaa8533/futures-util/src/future/future/map.rs#L34

**Comment by taiki-e** [comment]
Right. Also some `Fused{Future, Stream}` impls, including `Fuse`, should have similar issues.
And, this is one of the reasons I'd like to remove `Fused{Future, Stream}` (https://github.com/rust-lang/futures-rs/issues/2111#issuecomment-642279231).

**Comment by taiki-e** [comment]
As said in https://github.com/rust-lang/futures-rs/issues/2207#issuecomment-782050833, the current implementation is correct if the underlying types do not implement FusedFuture, but is incorrect if it is implemented.

Closing in favor of https://github.com/rust-lang/futures-rs/issues/2207, which propose the removal of FusedFuture.
