### ISSUE TITLE
Question: What happened to `futures-tls`?

### ISSUE THREAD

**Issue by xpepermint** [rust-lang/futures-rs#2218]
I'm searching for the `futures-tls` crate source and I don't see it in the master. The latest docs don't mention TLS as well. Was that functionality removed or moved?

**Comment by Nemo157** [comment]
It appears that `futures-tls` was split out to `tokio-tls` before 0.1.1 was released (which is the oldest tagged version, and 0.1.0 is yanked). See https://github.com/rust-lang/futures-rs/commit/b6936a1282a5a5ccb9cfcb032f09062fc19c2453
