### ISSUE TITLE
Trailing comma in macros triggers recursion limit

### ISSUE THREAD

**Issue by Victor-Savu** [rust-lang/futures-rs#2227]
Trailing commas in the arguments for the `join!` and `try_join!` macros trigger the recursion limit (probably due to infinite recursion):

```rust
let _ = join!(
  async { 1 },
  async { 2 }, // <-- this comma here
);
```
and
```rust
let _ = try_join!(
  async { Ok(1) },
  async { Ok(2) }, // <-- and this comma here
);
```

Error:
```
recursion limit reached while expanding `proc_macro_call_0!`
consider adding a `#![recursion_limit="256"]` attribute to your crate (`trailing_comma_futures`)
```

It would be great if trailing commas were accepted (and ignored), or at least if the error message were a bit more helpful.

**Comment by taiki-e** [comment]
FWIW, this should be supported 0.3.0-alpha.18 or later (https://github.com/rust-lang/futures-rs/commit/621d49119b3f24f0f15668b926fc354032d2a380): [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6400b086ee2671d1c5f6038d62a85f27)

**Comment by Victor-Savu** [comment]
Thank you, @taiki-e ! Indeed, I had an older version of the crate. However, while the simplified example I posted here works, my production code (where I initially ran into the problem) still fails due to a trailing comma, but it takes a few extra futures.

Here is a reproduction: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a21d88e6cdd4c2a24f5b7a2c4b82c1e7)

**Comment by Victor-Savu** [comment]
I think I misrepresented the problem. The trailing comma was a red herring. the error was due to the number of symbols that the macro has to parse (which makes sense).

**Comment by taiki-e** [comment]
That is a known limitation of `macro_roules!` macro: should be fixed by increase `recursion_limit` (add `#![recursion_limit="256"]` to lib.rs or main.rs) 

If increasing `recursion_limit` does not solve the problem, it is likely to be #2097.
