### ISSUE TITLE
stream::Chunks - preallocate on full buffer? 

### ISSUE THREAD

**Issue by stsydow** [rust-lang/futures-rs#2231]
While reading the docs and the code I stumbled upon https://github.com/rust-lang/futures-rs/blob/67566c65f5bba15dfad9d1d77e16d919bc18875f/futures-util/src/stream/stream/chunks.rs#L67 

It allocates the new underlying vector with default size while the chunk capacity in known.
I guess it should look like in Chunks::take():
https://github.com/rust-lang/futures-rs/blob/67566c65f5bba15dfad9d1d77e16d919bc18875f/futures-util/src/stream/stream/chunks.rs#L35

**Comment by Nemo157** [comment]
That line is only hit when the underlying stream is empty, so the new vector will never have any items pushed to it.

**Comment by stsydow** [comment]
sorry - I did not see that.
