### ISSUE TITLE
Missing StreamExt::unzip

### ISSUE THREAD

**Issue by LLFourn** [rust-lang/futures-rs#2234]
See [`core::iterator::unzip`]

[`core::iterator::unzip`]: https://doc.rust-lang.org/core/iter/trait.Iterator.html#method.unzip

**Comment by binier** [comment]
Are you looking for this?
https://github.com/rust-lang/futures-rs/blob/7340d3d5d6fe8082a73069582b048ebaef6626b1/futures-util/src/stream/stream/zip.rs#L56-L62

Or are you talking about a single stream which returns a tuple and you want unzip that into two streams?

**Comment by LLFourn** [comment]
>Or are you talking about a single stream which returns a tuple and you want unzip that into two streams?

Yes. This is what I wanted.
