### ISSUE TITLE
Missing synchronous version of `StreamExt::filter_map`

### ISSUE THREAD

**Issue by futpib** [rust-lang/futures-rs#2237]
|       | Map     | Filter & Map           |
|-------|------|------------|
| Sync (`-> T` callback)  | [`map`](https://docs.rs/futures/0.3.6/futures/stream/trait.StreamExt.html#method.map)  | :question:           |
| Async (`-> Future<T>` callback) | [`then`](https://docs.rs/futures/0.3.6/futures/stream/trait.StreamExt.html#method.then) | [`filter_map`](https://docs.rs/futures/0.3.6/futures/stream/trait.StreamExt.html#method.filter_map) |

I also wonder why `filter_map` was not called `filter_then`

**Comment by taiki-e** [comment]
Closing in favor of #2755.
