### ISSUE TITLE
Utility for polling a future from an async function

### ISSUE THREAD

**Issue by Plecra** [rust-lang/futures-rs#2257]
```rust
struct Check<'a, F: Future + ?Sized>(Pin<&'a mut F>);
impl<F: Future + ?Sized> Future for Check<'_, F> {
    type Output = Poll<F::Output>;
    fn poll(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        Poll::Ready(self.0.as_mut().poll(cx))
    }
}
async fn checkup(tasks: Vec<Task>) {
    for mut task in tasks {
        if let Poll::Ready(val) = Check(task.fut.as_mut()).await {
            handle(val);
            cleanup(task);
        }
    }
}
```

I've seen this pattern come up in a few different projects now, and it seems generic enough for the `futures` crate. It could well be too niche though.

**Comment by taiki-e** [comment]
This seems similar to use [`now_or_never`](https://docs.rs/futures/0.3.7/futures/future/trait.FutureExt.html#method.now_or_never) on (pinned) reference. (in this case, `task.fut.as_mut().now_or_never()`)

**Comment by Plecra** [comment]
It does look similar ☺️ The difference is that `Check` may be used multiple times, due to it being implemented on a pinned reference (`now_or_never` is implemented for all `T: Future`).

**Comment by taiki-e** [comment]
> The difference is that `Check` may be used multiple times, due to it being implemented on a pinned reference (`now_or_never` is implemented for all `T: Future`).

[Pinned future implements `Future`](https://docs.rs/futures/0.3.7/futures/prelude/trait.Future.html#impl-Future-for-Pin%3CP%3E), so I don't think this difference is a problem.

The actual difference is the context passed to the future. (`now_or_never` pass no-op context.) 
See also https://github.com/rust-lang/futures-rs/pull/1747#discussion_r305505139
