### ISSUE TITLE
Map of Futures or Streams

### ISSUE THREAD

**Issue by turnage** [rust-lang/futures-rs#2260]
I am interested in a structure similar to FuturesUnordered and SelectAll that allows users to insert, remove, and modify the stored futures and streams by a key at runtime.

Has there been any discussion about a feature like this for futures-rs? If not, I would be happy to write an RFC arguing for inclusion in this library.

**Comment by taiki-e** [comment]
FYI: tokio has a similar feature: https://docs.rs/tokio/0.3/tokio/stream/struct.StreamMap.html

**Comment by thomaseizinger** [comment]
> FYI: tokio has a similar feature: [docs.rs/tokio/0.3/tokio/stream/struct.StreamMap.html](https://docs.rs/tokio/0.3/tokio/stream/struct.StreamMap.html)

Unfortunately, tokio's `StreamMap` is not very efficient. It walks through the entire list and polls all streams (this shortcoming is documented). Additionally, the `tokio-stream` crate unconditionally depends on `tokio` itself despite `StreamMap` not requiring `tokio` at all.

It would be nice to have something that is equally efficient to `SelectAll` where only the `Stream`s that are ready are polled again.

My usecase is that I have a set of `mpsc::Receiver`s and I'd like to poll them concurrently but I want to know, which item originated from which `Receiver`. Most notably, I need to know, when a particular `Receiver` ends.

**Comment by taiki-e** [comment]
Closing in favor of #2329.
