### ISSUE TITLE
Remove .travis.yml

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/futures-rs#2264]
https://github.com/rust-lang/futures-rs/blob/73ade1e1598efe06e66df3d2b7926a1820cbfe0e/.travis.yml#L1-L2

Context: #2217
> It needs to change the "required statuses" of the branch protection settings to merge this (requires admin rights).

cc @cramertj: Could you change the branch protection settings?

**Comment by cramertj** [comment]
Done! Sorry for the delay.

**Comment by taiki-e** [comment]
@cramertj Thanks!
