### ISSUE TITLE
Rename FuturesUnordered.push() to add() or insert()

### ISSUE THREAD

**Issue by fleupold** [rust-lang/futures-rs#2266]
I'm not sure how much can realistically be done about this, but I wanted to give the feedback that I find the `FuturesUnordered.push` API slightly confusing. 

I associate `push` with Vectors or other ordered containers and as such when I read code using FuturesUnordered (especially in an environment that is not showing type hints) intuitively assume that the ordering in which futures are added to the combinator matters.

Maybe calling it `add` or `insert` instead of `push` would make it more clear to a `HashSet` and emphasise that the order in which we iterate over the results is not the order in which futures were added.

I'd be interested to hear if there was any deeper reason for that naming choice and understand that this might be hard to change now, so feel free to close this issue...

**Comment by taiki-e** [comment]
I would prefer not to do this for consistency with `FuturesOrdered`'s API.
 

> Maybe calling it `add` or `insert` instead of `push` would make it more clear to a `HashSet` and emphasise that the order in which we iterate over the results is not the order in which futures were added.

Note that set/map's `insert` is often an operation that may replace an existing value.
Also, I'm not sure if it's common in Rust to use `add` as the method name for collections. [At least `std` doesn't use it](https://doc.rust-lang.org/stable/std/index.html?search=add) (in `std`, `add` is basically a name for arithmetic methods).
