### ISSUE TITLE
missing lifetime specifier

### ISSUE THREAD

**Issue by venslu** [rust-lang/futures-rs#2269]
how to solve it?

work@ubuntu:~/tikv-rust/rust/test/demo$ cargo build --workspace
   Compiling demo v0.1.0 (/home/work/tikv-rust/rust/test/demo)
error[E0106]: missing lifetime specifier
  --> src/lib.rs:12:12
   |
12 |     addrs: & CxxVector<CxxString>,
   |            ^ expected named lifetime parameter
   |
help: consider introducing a named lifetime parameter
   |
11 | pub struct Address<'a> {
12 |     addrs: &'a  CxxVector<CxxString>,
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
error: could not compile `demo`.

To learn more, run the command again with --verbose.

**Comment by taiki-e** [comment]
As the help message said, can probably be solved by adding an explicit lifetime to struct and field.

> help: consider introducing a named lifetime parameter
> |
> 11 | pub struct Address<'a> {
> 12 | addrs: &'a CxxVector,
> |

PS: This question seems unrelated to futures-rs repository. For general rust questions, We recommend you to post in [the user forum](https://users.rust-lang.org/), not in this project. (In many cases, you will get an answer sooner.)
