### ISSUE TITLE
unresolved imports in futures::future following the loop_fn example

### ISSUE THREAD

**Issue by TheOnlyArtz** [rust-lang/futures-rs#2291]
Following this example https://docs.rs/futures/0.1.10/futures/future/fn.loop_fn.html

`loop_fn, FutureResult and loop` won't resolve.

I'm on Nightly channel of rust and using futures 0.3

**Comment by taiki-e** [comment]
> https://docs.rs/futures/0.1.10/futures/future/fn.loop_fn.html

> I'm on Nightly channel of rust and using futures 0.3

It seems you're looking at an older version of the documentation. loop_fn exists in 0.1 but not in 0.3.
