### ISSUE TITLE
Consider adding FuturesUnordered::clear() and SelectAll::clear()

### ISSUE THREAD

**Issue by erickt** [rust-lang/futures-rs#2327]
We're using `FuturesUnordered` to race multiple connection futures in order to implement the RFC 8305 Happy Eyeballs spec. Once we make a successful connection, we're supposed to close all the other pending connections in order to free up the resources. We are wrapping our `FuturesUnordered` in an `Option` to make sure we can drop any other pending connections as soon as possible.

However, it be simpler if we could just call a `FuturesUnordered::clear()` to throw away the futures. Likewise, I imagine a `SelectAll::clear()` could also be useful.

**Comment by taiki-e** [comment]
This seems reasonable to me. I would accept a PR to add this.

**Comment by ibraheemdev** [comment]
ah, yes, that is an easy delegation. I'll open a PR.
