### ISSUE TITLE
How to use Peekable with async_stream::stream?

### ISSUE THREAD

**Issue by mypetyak** [rust-lang/futures-rs#2331]
I'm having a hard time figuring out how to create a `Peekable` from a stream produced by the commonly-recommened [`async_stream::stream!` macro](https://docs.rs/async-stream/0.3.0/async_stream/macro.stream.html).

# What I'm trying to do
I'd like to peek at the next item in a stream, `s`, inside a loop, like this:
```
loop {
    let next = s.peek().await;
}
```

Since the receiver of [`Peekable::peek`](https://docs.rs/futures/0.3.12/futures/prelude/stream/struct.Peekable.html#method.peek) is `self: Pin<&mut Peekable<St>>`, I must pin the `Peekable` before I can call `peek`. Since pinning consumes the stream, I must pin inside the loop, like this:
```
loop {
    let pinned_s = Pin::new(&mut s);
    let next = pinned_s.peek().await;
}
```

# Where I'm stuck
However, if `s` is created by [`async_stream::stream!`](https://docs.rs/async-stream/0.3.0/async_stream/macro.stream.html), the compiler won't let me pin it because `s` is not `Unpin`.  Here's a full example:
```
use async_stream::stream;
use futures::stream::{Stream, StreamExt};
use std::pin::Pin;

fn make_stream() -> impl Stream<Item = u8> {
    stream! {
        loop {
            yield 0;
        }
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let s = make_stream();
    let mut p = s.peekable();
    loop {
        let pinned_p = Pin::new(&mut p);
        pinned_p.peek().await;
    }
}
```

To which the compiler says:
```
error[E0277]: `from_generator::GenFuture<[static generator@src/main.rs:6:5: 10:6 for<'r> {ResumeTy, &'r mut async_stream::yielder::Sender<u8>, async_stream::yielder::Sender<u8>, u8, impl futures::Future, ()}]>` cannot be unpinned
  --> src/main.rs:18:24
   |
18 |         let pinned_p = Pin::new(&mut p);
   |                        ^^^^^^^^ within `futures::stream::stream::fuse::_::__Origin<'_, impl Stream>`, the trait `Unpin` is not implemented for `from_generator::GenFuture<[static generator@src/main.rs:6:5: 10:6 for<'r> {ResumeTy, &'r mut async_stream::yielder::Sender<u8>, async_stream::yielder::Sender<u8>, u8, impl futures::Future, ()}]>`
```

The [`async_stream`](https://docs.rs/async-stream/0.3.0/async_stream/) library documentation indicates that the stream should be pinned to the stack _outside_ the loop, which would resolve the missing `Unpin` trait but prevent me from creating a useful pinned `Peekable` _inside_ the loop.

# Works fine with other streams
I have no issue using a `Peekable` with other streams like [`futures::stream::Repeat`](https://docs.rs/futures/0.3.12/futures/stream/struct.Repeat.html). For example, the below compiles just fine:
```
use futures::stream::repeat;
use futures::stream::StreamExt;
use std::pin::Pin;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    //let s = make_stream();
    let s = repeat(0);
    let mut p = s.peekable();
    loop {
        let pinned_p = Pin::new(&mut p);
        pinned_p.peek().await;
    }
}
```

# What am I missing?
As is probably clear, I'm still learning how to effectively use async streams and the role that pinning plays. But I think I've read all the available documentation on `Peekable`, `async_stream`, `pin_mut` and `std::pin::Pin`, and I can't figure out what I'm missing.  If someone can nudge me in the right direction, I'd like to help update the documentation for the benefit of other new folks.

**Comment by taiki-e** [comment]
You can fix compile error by combining pin_mut and reborrowing by [Pin::as_mut](https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html#method.as_mut).

```diff
      let p = s.peekable();
+     futures::pin_mut!(p);
      loop {
-         let pinned_p = Pin::new(&mut p);
+         let pinned_p = p.as_mut();
          pinned_p.peek().await;
      }
```

**Comment by mypetyak** [comment]
Ah, thank you @taiki-e.  This helps clarify two things I had misunderstood:

First, the below assumption isn't true:
> Since pinning consumes the stream, I must pin inside the loop

Pinning does consume the stream, but I can pin the stream outside the loop and borrow it from the `Pin` inside the loop via [`Pin::as_mut`](https://doc.rust-lang.org/std/pin/struct.Pin.html#method.as_mut).

Second, the compiler wouldn't allow me to use `Pin::new` to pin the results from `async_stream::stream!` because the resulting `AsyncStream` isn't `Unpin`. _This_ is why `Futures::pin_mut!` is useful: it allows the safe creation of a `Pin<&mut Foo>` in cases when `Foo` is not `Unpin`.

Previously, I didn't really understand `pin_mut!`, but I think I have a better handle on it now. Thanks again!
