### ISSUE TITLE
`select` example in docs

### ISSUE THREAD

**Issue by tungli** [rust-lang/futures-rs#2334]
I am an async noob but the 'simple example' in [docs](https://docs.rs/futures/0.3.12/futures/future/fn.select.html) on `select` may be a bad example.
The example `select`s one of the futures:
```rust
let future1 = async { 1 };
let future2 = async { 2 };
```
The problem in this is that the computations are both `Poll::Ready` immediately (at least on my machine).
So the result of the `select` is always `Either::Left`, as I would expect from [the implementation](https://github.com/rust-lang/futures-rs/blob/master/futures-util/src/future/select.rs#L92).
Therefore, the `assert!` in the example is misleading IMHO.

I would suggest being explicit about one future finishing first.
The simplest example I came up with is [here](https://gist.github.com/tungli/f89599edd09ab192707c9df2b56a06c8).

**Comment by taiki-e** [comment]
I would accept a PR that improves this example.

**Comment by tungli** [comment]
Thanks @taiki-e! Created the PR #2345
