### ISSUE TITLE
`StreamExt::buffered` and `StreamExt::buffer_unordered` hangs for `n = 0`

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/futures-rs#2348]
Try the following code:

```rust
use futures::executor;
use futures::stream::{self, StreamExt};
use std::future;

fn main() {
    executor::block_on(async {
        let mut s = stream::iter(0..10).map(future::ready).buffered(0);

        while let Some(value) = s.next().await {
            println!("{}", value);
        }
    });
}
```

Is this the expected behavior?

**Comment by taiki-e** [comment]
I *feel* this is a bug. I think it's preferable to panic if capacity is 0, like chunks.

https://github.com/rust-lang/futures-rs/blob/e981716f47936ea31aa4d262fd01816749f094b1/futures-util/src/stream/stream/chunks.rs#L26
