### ISSUE TITLE
Consider exposing Fn*1-traits publicly

### ISSUE THREAD

**Issue by b3t33** [rust-lang/futures-rs#2349]
I would like to wrap a tokio receiver into a stream using `stream::unfold()` while giving a concrete type. As the used closure's type is not available (and Fn-traits are not implementable on stable), this cannot be done yet.

However, there are already the wrapper traits in [fns.rs](https://github.com/rust-lang/futures-rs/blob/master/futures-util/src/fns.rs). Exposing them publicly and using them in `stream::unfold()` (and possibly more places) would allow for concrete types. This is already done (internally) e.g. for [`FuturesExt::map_into()`](https://github.com/rust-lang/futures-rs/blob/4124111369d1f69a07183fccc7d97006e8846008/futures-util/src/future/future/mod.rs#L64).

As a downside the api would look a little more cluttered, when replacing trait bounds like `FnMut(A) -> O` by `FnMut1<A>`.

**Comment by taiki-e** [comment]
Closing based on the decision in #2355
