### ISSUE TITLE
futures-core 0.3.7 is breaking

### ISSUE THREAD

**Issue by leo60228** [rust-lang/futures-rs#2361]
The following chain of events can lead to futures-util failing to build despite none of the steps being individually abnormal:

1. Add futures-util 0.3.6 as a dependency.
2. Later, add a dependency depending on a newer version of futures-core.

Here's a repo demonstrating this (check the commit history): https://github.com/leo60228/futures-test

```
error[E0432]: unresolved import `futures_core::core_reexport`
  --> /home/leo60228/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.6/src/lib.rs:55:9
   |
55 | pub use futures_core::core_reexport;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `core_reexport` in the root
```

This is because `futures-core` 0.3.7 removed `core_reexport`. This seems like it should be fine, since it's only used internally by `futures`, but mismatched subcrate versions can cause this issue.

**Comment by taiki-e** [comment]
Fixed by https://github.com/rust-lang/futures-rs/pull/2233 (0.3.7) that removing the dependency on private API.
