### ISSUE TITLE
StreamExt::flat_map_unordered

### ISSUE THREAD

**Issue by khuey** [rust-lang/futures-rs#2378]
(Inspired by the twitter thread at https://twitter.com/RReverser/status/1374544426622726145)

Flattening a stream of streams into a single stream provides an opportunity for concurrency if you don't care about the output order of the final stream. An efficient solution is difficult to realize with the built-in combinators.

- StreamExt::flat_map doesn't offer any concurrency
- stream::select_all requires collecting the stream of streams into an iterable.
- Using StreamAll directly can be done with StreamExt::collect, but it still requires collecting all streams from the stream of streams first before processing any of the output items.

What is really desired in this case is a combinator that introduces concurrency both within the set of streams yielded by the stream of streams and with the stream of streams itself. Something like (pseudocode)

```
    let stream_of_streams = ...;
    let accumulated_streams = SelectAll::new();
    loop {
        match select(stream_of_streams.next(), accumulated_streams.next()).await {
           StreamOfStreamsBranch(new_stream) => accumulated_streams.push(new_stream);
           AccumulatedStreamsBranch(item_to_pass_along) => break item_to_pass_along,
        }
    }
```

**Comment by taiki-e** [comment]
https://github.com/rust-lang/futures-rs/issues/1781 https://github.com/rust-lang/futures-rs/pull/2083
