### ISSUE TITLE
eixsts “expected item after attributes" when use "#[derive(Debug)];" in rustc 1.5.1

### ISSUE THREAD

**Issue by VegeBun-csj** [rust-lang/futures-rs#2394]
eixsts “expected item after attributes" when use "#[derive(Debug)];" in rustc 1.5.1

**Comment by taiki-e** [comment]
Please provide the context in which the error occurred and the full error message.

**Comment by VegeBun-csj** [comment]
> Please provide the context in which the error occurred and the full error message.

OK，this problem was resolved
