### ISSUE TITLE
WeakShared is not Clone

### ISSUE THREAD

**Issue by hlb8122** [rust-lang/futures-rs#2395]
[WeakShared](https://docs.rs/futures/0.3.14/futures/future/struct.WeakShared.html) is not `Clone`, despite [Weak](https://doc.rust-lang.org/std/rc/struct.Weak.html#impl-Clone) which it wraps being `Clone`.

I can put in a PR if required.

**Comment by taiki-e** [comment]
Good catch. I would accept a PR to add Clone impl.
