### ISSUE TITLE
Removing `proc_macro_hack`

### ISSUE THREAD

**Issue by Ciantic** [rust-lang/futures-rs#2406]
The macros using `proc_macro_hack` like `select!`, `try_join!` don't work with Rust Analyzer ( https://github.com/rust-analyzer/rust-analyzer/issues/6835 ).

I don't know what is required to remove `proc_macro_hack`, but given that [it's page](https://github.com/dtolnay/proc-macro-hack) says:

> Note: As of Rust 1.45 this crate is superseded by native support for #[proc_macro] in expression position. Only consider using this crate if you care about supporting compilers between 1.31 and 1.45.

It could be replaceable with `proc_macro`, which has better support.

**Comment by taiki-e** [comment]
we can't remove proc_macro_hack as we need to support old compilers but can use `#[proc_macro]` at Rust 1.45+

**Comment by taiki-e** [comment]
Released in 0.3.15.
