### ISSUE TITLE
adding loop_fn_back in to the future-rs

### ISSUE THREAD

**Issue by warlord500** [rust-lang/futures-rs#2444]
I have created a small library that isn't entirely completed but almost there to add loop fn back in, 
I wasn't entirely sure how I would alter the mod files to add it in but i think there 

the library is at 
[https://github.com/warlord500/loop_fn_future](https://github.com/warlord500/loop_fn_future)

**Comment by ibraheemdev** [comment]
Quickly reviewing the implementation, you could use `futures_core::ready` instead of the macro yourself and `pin-project-lite` instead of `get_unchecked_mut`.

**Comment by taiki-e** [comment]
What is the use case for this? 

Historically, this function has been removed in favor of `loop` + `async/await`. [Looking at the previous discussion](https://github.com/rust-lang/futures-rs/pull/980#issuecomment-488831746) it could be useful in migrating from 0.1, but it's really temporary and I don't want to enable it by default.

In any case, I would like to know about specific use cases that require this.

**Comment by taiki-e** [comment]
I would prefer not to add this unless there is a specific use case that requires this.
