### ISSUE TITLE
`StreamExt::All / StreamExt::Any`

### ISSUE THREAD

**Issue by barvirm** [rust-lang/futures-rs#2458]
Is there a reason why these methods aren't implemented?
Both of these can be implemented with fold, or Am'I missing something?

**Comment by taiki-e** [comment]
I don't think there is any reason other than "no one has ever requested it before. 

I would accept a PR to add them.

**Comment by barvirm** [comment]
[https://github.com/rust-lang/futures-rs/pull/2460](https://github.com/rust-lang/futures-rs/pull/2460)
