### ISSUE TITLE
Is there a (Try)StreamExt equivalent to Iterator's find_map()?

### ISSUE THREAD

**Issue by kit-981** [rust-lang/futures-rs#2462]
I have an iterator that I want to `map` and return the first _successful_ result. I would usually do this using the `find_map` method from the [Iterator trait](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find_map). In this case, however, I need to call an `async` function in the closure.

From what I understand, this requirement means that I need to convert the iterator to a stream so that I can provide a closure that's capable of suspending. I don't see any methods like `find_map` in [StreamExt](https://docs.rs/futures/0.3.15/futures/stream/trait.StreamExt.html) or [TryStreamExt](https://docs.rs/futures/0.3.15/futures/stream/trait.TryStreamExt.html) though.

Is there any chance someone has an example demonstrating behaving like `find_map`? Is there a recommended way for doing what I want to? I don't have much experience with asynchronous programming in Rust so I'm not sure where I should be looking.

Thanks.

**Comment by taiki-e** [comment]
How about https://docs.rs/futures/0.3.15/futures/stream/trait.StreamExt.html#method.flat_map ?

**Comment by kit-981** [comment]
I might be misunderstanding `flat_map` but it looks like it does a transformation on all the elements in the iterator and does not short circuit in the same way `find` or `find_map` might. I'm hoping to run the `async` closure against each of the iterator members *until* one returns a successful result (`Some` or `Ok` for instance).

**Comment by Lucretiel** [comment]
I don't think there's a dedicated method for this; the solution would be `stream.filter_map(|item| async { ... }).next()`

**Comment by kit-981** [comment]
> I don't think there's a dedicated method for this; the solution would be `stream.filter_map(|item| async { ... }).next()`

Thanks for confirming that there is no dedicated method. I'll use the suggestion that you provided.
