### ISSUE TITLE
`impl IntoStream for Iterator`?

### ISSUE THREAD

**Issue by ShadowJonathan** [rust-lang/futures-rs#2463]
(I know that title doesn't make sense, but it's pseudocode, bear with me)

I recently tried out this little tidbit, and i was surprised that `futures` doesn't allow it;
```rs
Ok(self
    .iter_ids()? // impl Iterator<Item = Result<_, _>> + Send
    .filter_map(|id| id.ok()) // impl Iterator<String>
    .into_stream() // impl Stream?
    .then(move |id| async {
        Ok((
            id.clone(),
            self.get_registration(&id)
                .await?
                .expect("iter_ids only returns appservices that exist"),
        ))
    }))
```
Are there any plans to allow something like this?

**Comment by taiki-e** [comment]
You can use [`stream::iter`](https://docs.rs/futures/0.3.15/futures/stream/fn.iter.html) for this purpose.

See https://github.com/tokio-rs/tokio/pull/3106#pullrequestreview-525650727 for why this is an explicit function call rather than an unconditional trait implementation for iterators.
