### ISSUE TITLE
Safety risk with reusing ReadyToRunQueue

### ISSUE THREAD

**Issue by erickt** [rust-lang/futures-rs#2473]
In Fuchsia, we performed an [audit of Futures 0.3.15](https://fuchsia-review.googlesource.com/c/fuchsia/+/567474), and we noticed that [ReadyToRunQueue::drop](https://github.com/rust-lang/futures-rs/blob/0c4d6a38f3929ff9e1a7c56f655173262197d736/futures-util/src/stream/futures_unordered/ready_to_run_queue.rs#L111) is not inherently safe, and instead relies on `FuturesUnordered::drop` to execute first.

As best as we can tell, this appears to be safe, but there's a risk that if `ReadyToRunQueue` is ever used elsewhere, it would be pretty easy to miss this safety constraint. Is there a way we could protect against this? At a minimum, I think it might be worth adding a `// Safety: ...` comment to the struct definition describing this requirement, but perhaps there's a way to refactor the code to avoid this risk all together.

cc @anp and @ibraheemdev

**Comment by ibraheemdev** [comment]
The best way is probably to make `ReadyToRunQueue::drop/clear` an inherent unsafe method, and call it in `FuturesUnordered::drop` with the safety guarantee.
