### ISSUE TITLE
Use futures-util without macros

### ISSUE THREAD

**Issue by ibraheemdev** [rust-lang/futures-rs#2474]
`futures-util` currently *always* pulls in syn, quote, proc-macro2 and others because of futures-macro, there should be a way to disable that.

**Comment by taiki-e** [comment]
futures-macro is already optional and only default and async-await-macro use it.
https://github.com/rust-lang/futures-rs/blob/62d5aa5c0512f2ad0587d26e7f2ee2b4b109469a/futures-util/Cargo.toml#L43
https://github.com/rust-lang/futures-rs/blob/62d5aa5c0512f2ad0587d26e7f2ee2b4b109469a/futures-util/Cargo.toml#L19
