### ISSUE TITLE
Suboptimal error message when FuturesExt is not `use`'d

### ISSUE THREAD

**Issue by nipunn1313** [rust-lang/futures-rs#2478]
Here is an example:
```
error[E0599]: the method `map` exists for opaque type `impl futures::Future`, but its trait bounds were not satisfied
  --> src/protocol.rs:29:46
   |
29 |         self.client.get(url.as_str()).send().map(|r| {
   |                                              ^^^ method cannot be called on `impl futures::Future` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `impl futures::Future: Iterator`
           which is required by `&mut impl futures::Future: Iterator`
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use futures::FutureExt;`
```

I think - this is the most relevant advice
```
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use futures::FutureExt;`
```

The other one about Future: Iterator - feels fairly rare to be the one looking for here.
Only a minor usability concern, but if there's some precedent for sorting the suggestions by usefulness.

I may be off base here (maybe both suggestions are equally valid in different contexts, of which I only understand one). I've been using Futures since pre 1.0, so I may just have bad muscle memory here, but I personally found this confusing.

**Comment by ibraheemdev** [comment]
You can file an issue in rust-lang/rust, this is not actionable here.
