### ISSUE TITLE
Lifetime issues around write_vectored et al

### ISSUE THREAD

**Issue by ejmount** [rust-lang/futures-rs#2483]
(I first spotted this while trying to use `write_all_vectored` within `AsyncWriteExt`, but the same applies elsewhere in that trait.)

The signature of fn `write_all_vectored` is, 
```
fn write_all_vectored<'a>(&'a mut self, bufs: &'a mut [IoSlice<'a>]) -> WriteAllVectored<'a, Self>
```

I don't understand this choice of lifetimes, particularly the `&'a Something<'a>` construction, which I have gathered is suggestive of a self-refential struct and should be avoided. When I tried to charge ahead and use the function anyway, I got very confusing lifetime errors about my structure being borrowed at the point where it's dropped. I asked at URLO, and they suggested to report this as a bug. 

To understand more, I tried re-implementing it while making all three lifetimes independent (ala [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c4272b1a0a92225224c080cb5ccb400a)) but this appeared to work exactly as intended, which just left me further mystified. Does making all the lifetimes the same serve a purpose I've missed, or is this truly a bug?

If this is a bug and the playground snippet I've posted is the correct resolution, I'd be quite happy to raise a PR for it and corresponding changes to other parts of `AsyncWriteExt`, I just wanted to check that this was truly a mistake first.

Additionally, for `write_all_vectored` in particular, the documentation suggests that `bufs` is unusable and in an undefined state after the function completes. I similarly cannot see any reason why it was not consumed if that's the case.

**Comment by ibraheemdev** [comment]
This does look overly restrictive, adding a second lifetime should do:
```rust


fn write_all_vectored<'a>(&'a mut self, bufs: &'a mut [IoSlice<'a>]) -> WriteAllVectored<'a, Self>

**Comment by ejmount** [comment]
Since it was how the problem arose in the first place, my inclination would be to make lifetimes as independent as possible, (which would affect methods like `write`/`write_all`) but it makes less difference than I initially thought because the members aren't externally accessible anyway. 

And just for reference, is there anything to be done about `bufs`? Obviously changing the signature to take by ownership would be a much more impactful change than the lifetimes, but should it be made anyway?

**Comment by Nemo157** [comment]
The problem is there is no way to take a slice by ownership (without allocation).
