### ISSUE TITLE
documentation for select! macro

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/futures-rs#2511]
https://github.com/rust-lang/futures-rs/blob/3601bb76708ea4bcc14c3491237abc33b685ba0b/futures-util/src/async_await/select_mod.rs#L32-L33

With this [commit](https://github.com/rust-lang/futures-rs/commit/8666a25d8dbb7c3418f3b98946afc4e7e40e8f33) , is the above statement still accurate?  Is it true that `select!` macro only uses `proc-macro-hack` if rustc version older than 1.45?  Do we still need to worry about `recursion_limit`?

**Comment by taiki-e** [comment]
Good catch. It's definitely outdated; if you're using Rust 1.45+, you won't have the problem.
