### ISSUE TITLE
new many_threads test failure in futures 0.3.19 on armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by decathorpe** [rust-lang/futures-rs#2539]
I'm running the futures-rs test suite during our package builds on Fedora linux to make sure this important part of the ecosystem works as expected. In futures 0.3.19, I encountered a new test failure on linux 32-bit ARM targets, from `futures/tests/future_shared.rs::many_threads`:

```
(...)
test many_threads ... FAILED
failures:
---- many_threads stdout ----
thread 'many_threads' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /builddir/build/BUILD/rustc-1.57.0-src/library/std/src/thread/mod.rs:630:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    many_threads
test result: FAILED. 9 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s
```

Or, during another test run:

```
(...)
test many_threads ... FAILED
failures:
---- many_threads stdout ----
thread 'many_threads' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /builddir/build/BUILD/rustc-1.57.0-src/library/std/src/thread/mod.rs:630:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', tests/future_shared.rs:26:52
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', tests/future_shared.rs:26:52
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', tests/future_shared.rs:26:52
failures:
    many_threads
test result: FAILED. 9 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s
```

Is this test known to be flaky? I ran three builds of futures 0.3.19; two failed with the errors above, one succeeded.

---

- rustc 1.57.0 on Fedora Rawhide / 35 / 34
- rustc target: armv7-unknown-linux-gnueabihf

**Comment by taiki-e** [comment]
This seems to be a problem with the resources of the host machine. [That test](https://github.com/rust-lang/futures-rs/blob/dacf2565d4adfa978b342770190b9a6a1c56329a/futures/tests/future_shared.rs#L51) tries to spawn 1000 threads simultaneously, but the machine you used for the test does not seem to be able to handle that amount of threads.

(However, this test hasn't been changed in a long time, so it's a bit odd that this issue has happened so recently...)

**Comment by taiki-e** [comment]
I think a reasonable fix would be to reduce the number of threads spawned when the target is 32bit, but I don't have an armv7hf linux machine, so I don't know how much reduction is reasonable.

**Comment by decathorpe** [comment]
I suspected that this might be due to resource constraints. It's possible that our build hosts were just unusually busy when I launched the futures 0.3.19 builds, but at least now I know that I can safely ignore that test failure for now, so thanks for confirming my suspicions. Should we close this ticket?

**Comment by taiki-e** [comment]
Yeah, I'm going to close this for now.
