### ISSUE TITLE
futures::stream::SelectAll infinite loop of None when it is empty in dynamic use.

### ISSUE THREAD

**Issue by SajjadPourali** [rust-lang/futures-rs#2557]
SelectAll supports push to make it possible for dynamic uses; in other words, push streams after await.
In this case, when the SelectAll has only initialized without any prior items, the next() always [returns None](https://docs.rs/futures-util/latest/src/futures_util/stream/select_all.rs.html#99) instead of waiting for a new stream when called; it always returns None instead of waiting for a new Ready stream, which uses of it is a select! Macro makes it an infinity loop until a push happens.
I push a junk pending stream that never drops to evade the loop, which is not a good idea.

**Comment by taiki-e** [comment]
I don't know what the problem you are talking about is.

If the `FuturesUnordered` is empty, `None` will be returned.

https://github.com/rust-lang/futures-rs/blob/64643712ffd2e86f875d0696831bebddf01db3f4/futures-util/src/stream/select_all.rs#L111

The `Some((None, _))` branch is reached when the `FuturesUnordered` is not empty, but the stream that is pushed to `SelectAll` is empty. The empty stream will not be pushed again, so the same branch will not be repeated.

https://github.com/rust-lang/futures-rs/blob/64643712ffd2e86f875d0696831bebddf01db3f4/futures-util/src/stream/select_all.rs#L105-L110

**Comment by SajjadPourali** [comment]
I think my explanation wasn't straightforward enough.

> The empty stream will not be pushed again, **_so the same branch will not be repeated_**.


I believe that It can!
Please take a look to the following pseudo code to understand the issue.

```
let mut test = futures_util::stream::SelectAll::new();
loop{
    tokio::select! {
        Some(another_rx)=event_rx.recv()=>{
            test.push(another_rx)=);
        },
        msg = test.next() => {
            println!("{:#?}", msg);
        },
    }
}

```
event_rx is a MPSC Receiver that receives another MPSC Receiver from a spawn. In this case it always None instead block for resolve.

**Comment by taiki-e** [comment]
ok, this seems the same issue as https://github.com/rust-lang/futures-rs/issues/1009. select_next_some + our select macro can handle this.

**Comment by SajjadPourali** [comment]
Oh I see, Thanks.
