### ISSUE TITLE
UB in futures::join macro?

### ISSUE THREAD

**Issue by pro465** [rust-lang/futures-rs#2572]
the `futures::join` macro seems to be checking if all of the futures returned `Poll::Ready`, and if not, calls `poll` on all of them again, regardless of if some of them previously had returned `Poll::Ready`. 

this, if i understand correctly, violates the `poll` contract:
> Once a future has finished, clients should not poll it again.

**Comment by ibraheemdev** [comment]
1. This wouldn't be *undefined behavior*, just *unspecified*.
2. Futures are wrapped in `MaybeDone`, which drops the inner future the first time it returns `Ready` retaining the value.

**Comment by pro465** [comment]
@ibraheemdev I was trying to learn the internals of async/.await and was a bit confused by this, so thank you for clearing it up!

**Comment by pro465** [comment]
closing issue...
