### ISSUE TITLE
Add `Option::<Fut>::into_fut(self) -> OptionFuture<Fut>` extension method

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/futures-rs#2581]
As for now it is highly unergonomic to create `OptionFuture`. To do this you need to either do an explicit call `OptionFuture::from(val)` or assign the result into an intermediate variable `let temp: OptionFuture<_> = val.into()`, which disrupts the method call chain.

I propose to add the following extension trait to this crate natively to support undisrupted method call chains for optional futures:

```rust
pub trait OptionExt<Fut> {
    fn into_fut(self) -> OptionFuture<Fut>;
}

impl<Fut> OptionExt<Fut> for Option<Fut>
where
    Fut: Future
{
    fn into_fut(self) -> OptionFuture<Fut> {
        self.into()
    }
}
```

## Unresolved questions

There is a similar conversion for `Option<Result<T>> -> Result<Option<T>>`, which is named `transpose()` in std. Unfortunatelly that naming doesn't scale natively. We could use `transpose_fut()` method name here, but neither name is the best...

**Comment by taiki-e** [comment]
I feel this is an issue that should be handled by the IntoFuture trait in the standard library.
