### ISSUE TITLE
Make `FuturesOrdered` parallel

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/futures-rs#2594]
It could use rayon, for example.

**Comment by taiki-e** [comment]
Do you mean you want something like [JoinSet](https://docs.rs/tokio/latest/tokio/task/struct.JoinSet.html)?

If so, pushing the join handles of the tasks spawned from the multithreaded executor to the FuturesOrdered should work.

**Comment by Milo123459** [comment]
Yeah, that's what I needed. Sorry.

**Comment by ibraheemdev** [comment]
> If so, pushing the join handles of the tasks spawned from the multithreaded executor to the FuturesOrdered should work.

There isn't really any benefit of waiting on join handles concurrently though, it's just extra overhead compared to a `Vec`.
