### ISSUE TITLE
Collect/TryCollect does not use Stream::size_hint

### ISSUE THREAD

**Issue by jhgg** [rust-lang/futures-rs#2617]
I was reading through the implementation of collect/try_collect, and realized that the size_hint of the stream was not being used. Is there any good reason for this, or is this just a bug/not yet implemented?

**Comment by taiki-e** [comment]
In the current API, unstable Extend::extend_reserve (https://github.com/rust-lang/rust/issues/72631) is needed to use size_hint. See also #1833.
