### ISSUE TITLE
https://github.com/rust-lang/futures-rs/pull/2583 introduced regression in `select_with_strategy`

### ISSUE THREAD

**Issue by Sushisource** [rust-lang/futures-rs#2634]
Hello,

Recently updated my deps and started encountering all sorts of weird errors.

Narrowed it down to likely being something with `select_with_strategy`, and looking at the change notes I suspect this line of code [here](https://github.com/rust-lang/futures-rs/pull/2583/files#diff-14cac167b5abaf338792061c2718e3f8df1864fe00d9a1d652f4583b5bce22beR56) is the source of my problems.

I am (as in the example [here](https://docs.rs/futures-util/latest/futures_util/stream/fn.select_with_strategy.html#priority)) using an always-select-left strategy. The problem with the new code is that, if the right stream terminates, such a strategy now considers the combined stream as terminated.

I have created a PR [here](https://github.com/rust-lang/futures-rs/pull/2635) for the fix ~, but have not had time to add a test quite yet. There should definitely be one though, clearly.~

**Comment by taiki-e** [comment]
cc @414owen

**Comment by 414owen** [comment]
It's quite possible that I've introduced a regression, but I don't it would be in the lines you linked. 

I've [commented](https://github.com/rust-lang/futures-rs/pull/2635#issuecomment-1216548128) on your PR with more detail.
