### ISSUE TITLE
Add a combinator for converting an `Option<Future>` into a `Future<Option>`

### ISSUE THREAD

**Issue by notgull** [rust-lang/futures-rs#2637]
Consider the following code, where `bar` is an async function:

```
let foo = Some(24);

foo.map(|foo| bar(foo))
```

The end result of this is an `Option<impl Future>`. In order to `await` or `poll()` this future, it needs to be matched on or unwrapped, which may be messy or undesired.

I propose a combinator to the tune of `into_future()`, with a public API like this:

```
trait OptionExt<F> {
    fn into_future(self) -> IntoFuture<F>;
}

struct IntoFuture<F>(Option<F>);

impl<F: Future> Future for IntoFuture<F> {
    type Output = Option<F::Output>;
}
```

This may also be useful for `Result`.

**Comment by Veetaha** [comment]
Discussed this in https://github.com/rust-lang/futures-rs/issues/2581, however Rust std wasn't extended with `impl IntoFuture for Option<Fut>` :cry:

**Comment by notgull** [comment]
Ah, I see.
