### ISSUE TITLE
Add function that produces a stream from a future that produces a stream

### ISSUE THREAD

**Issue by vadixidav** [rust-lang/futures-rs#2642]
I looked through the current issues and could not find where anyone else has had this issue thus far, but this may be solved using a pattern I am not aware of currently.

I came across this issue when using `iced::Subscription`. [One of the maintainers is relying on the `stream`, `Stream`, and `StreamExt` API to provide a broad set of APIs for creating subscriptions](https://github.com/iced-rs/iced/discussions/1408#discussioncomment-3378924). Therefore, I think an issue I had originally raised on the `iced` repository actually belongs here.

The issue is that I need to return a `Stream` from a synchronous context. Internally, the `Stream` needs to await on the creation of an inner stream. In this case, the inner stream is connecting to a serial port and performing some communication before it can be established, all of which requires the use of `async`. Ideally, this is how I imagine this API (here called `futures::stream::eventually`) would work with `iced::Subscription`:

```rust
impl<Hasher, Event> Recipe<Hasher, Event> for Stew
where
    Hasher: std::hash::Hasher,
{
    type Output = Message;

    fn hash(&self, state: &mut Hasher) {
        self.port.hash(state);
    }

    fn stream(self: Box<Self>, _: BoxStream<'static, Event>) -> BoxStream<'static, Message> {
        futures::stream::eventually(async move {
            let port = tokio_serial::new(&*self.port, 921600)
                    .open_native_async()
                    .ok()?;
            // some setup here using the port
            // create and return the stream here
        }).fuse().boxed()
    }
}
```

Does this seem like something that should be added to the `stream` API? Also, are there trivial alternatives that I am just not seeing?

**Comment by taiki-e** [comment]
Does `once`+`flatten` not work?

**Comment by vadixidav** [comment]
Actually, yes, once + flatten would work. I hadn't considered that solution, as the idea of sending a stream over a stream didn't occur to me. Feel free to close this issue then, unless you think it would be a good idea to add another API. I will adapt my code to use once + flatten.
