### ISSUE TITLE
read_until seems not to work correctly on Windows 11

### ISSUE THREAD

**Issue by craigkai** [rust-lang/futures-rs#2671]
Using the following code:

```rust
 let mut reader = BufReader::new(connection);
 let mut my_str = vec![];

if let Err(error) = reader.read_until(0xA, &mut my_str) {....}
```

Where I am reading some data from a serial connection. On Linux & Mac I see the read_until function executing quite fast, but on Windows (11) I see the serial connection's timeout (500ms) is what is ending the read_until command -- Which does then proceed to do the correct thing after with the correct value in the buffer. It is just comparatively slow.

An example of the output I am seeing:
```
Successfully sent write to serial: CONFIG
Successfully read from serial "0\n"
Successfully sent write to serial: ILLUMDAY
Successfully read from serial "10\n"
Successfully sent write to serial: ILLUMNIGHT
Successfully read from serial "25\n"
Successfully sent write to serial: ILLUMMODE
Successfully read from serial "0\n"
Successfully sent write to serial: ECHO
Successfully read from serial "0\n"
Successfully sent write to serial: ANIM
Successfully read from serial "0\n"
```

Is this some kind of bug with Windows or am I missing something obvious? Thanks for any input!

**Comment by taiki-e** [comment]
What is the type of `connection`? This crate does not provide networking primitives and does not have OS-specific code, so if this is a library-side issue, it is likely a problem with the crate providing the type of `connection`.

**Comment by craigkai** [comment]
The connection is a [serialport](https://docs.rs/serialport/latest/serialport/) connection
