### ISSUE TITLE
then_concurrent / map_concurrent

### ISSUE THREAD

**Issue by FredrikNoren** [rust-lang/futures-rs#2692]
Hi,

I'm sure I'm missing something, but I'm trying to find something like `for_each_concurrent`, but which will let me return a list of items too. `then_concurrent` doesn't exist; is there some other method that I'm missing? This is for a regular stream constructed with `futures::stream::iter`.

I.e., I'd like to do something like this:
```rust
let res = futures::stream::iter(files.iter())
  .then_concurrent(None, |file| tokio::spawn(async move { process(file) }).await.unwrap())
  .collect().await;
```
and have it process the files in parallel.

**Comment by taiki-e** [comment]
I think buffer_unordered/buffer + map/then works as such. See also #2609.
