### ISSUE TITLE
`AsyncRead/Write` on `AllowStdIo` can return `0`

### ISSUE THREAD

**Issue by daxpedda** [rust-lang/futures-rs#2713]
I noticed when wrapping `std::io::Read/Write` types in `AllowStdIo` can return `0`, which is allowed by `std::io::Read/Write` but I believe not by `AsyncRead/Write`.

[`std::io::Read`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#tymethod.read):
> If `n` is `0`, then it can indicate one of two scenarios:
>
> 1. This reader has reached its "end of file" and will likely no longer
>    be able to produce bytes. Note that this does not mean that the
>    reader will *always* no longer be able to produce bytes. As an example,
>    on Linux, this method will call the `recv` syscall for a [`TcpStream`],
>    where returning zero indicates the connection was shut down correctly. While
>    for [`File`], it is possible to reach the end of file and get zero as result,
>    but if more data is appended to the file, future calls to `read` will return
>    more data.
> 2. The buffer specified was 0 bytes in length.

[`AsyncRead`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#errors):
> This function may not return errors of kind `WouldBlock` or
> `Interrupted`.  Implementations must convert `WouldBlock` into
> `Poll::Pending` and either internally retry or convert
> `Interrupted` into another error kind.

Not entirely sure if `0` is allowed by `AsyncRead/Write`, but it just means EOF, so it should return `io::ErrorKind::UnexpectedEof` if possible.

Did I miss something here or is that actually a bug?

**Comment by taiki-e** [comment]
I think Async* follows std::io traits' behavior unless explicitly documented otherwise. (We did not choose to copy and maintain all documents from std::io.)

**Comment by daxpedda** [comment]
Alright, good to know :+1:!

Maybe it could be clearer if it was explicitly stated that it follows `std::io` traits' behavior unless stated otherwise?
It's totally understandable that you didn't choose to copy and therefore maintain all the documentation!
