### ISSUE TITLE
[question] is pin-project on SelectAll necessary?

### ISSUE THREAD

**Issue by yshui** [rust-lang/futures-rs#2724]
https://github.com/rust-lang/futures-rs/blob/8253b784fd45c832ad208d5b8e259f639fc42684/futures-util/src/stream/select_all.rs#L16-L34

`FuturesUnordered` itself is `Unpin`, did I miss something?

**Comment by yshui** [comment]
Similarly, I think `SelectAll` doesn't need `St: Unpin` to implement `Stream`

**Comment by taiki-e** [comment]
Yeah, I don't think pin projection is needed here. https://github.com/rust-lang/futures-rs/pull/2431 removed the need for it but forgot to remove it.


> For the same reason, I think `SelectAll` doesn't need `St: Unpin` to implement `Stream`

IIRC, it is required by StreamFuture.

**Comment by yshui** [comment]
> it is required by StreamFuture.

Indeed! sorry I missed that :sweat_smile:
