### ISSUE TITLE
Consider pollster as the futures_executor::block_on implementation

### ISSUE THREAD

**Issue by e00E** [rust-lang/futures-rs#2739]
This is related to https://github.com/zesterer/pollster/issues/21 where I ask what differences between pollster and futures_executor. Both crates aim to accomplish the same thing so why duplicate the effort. I didn't find a mention of pollster in this repository so here I am bringing it up.

**Comment by notgull** [comment]
Personally, I would say that the minimal duplicated effort is worth it compared to the trade off of adding a new dependency.

**Comment by taiki-e** [comment]
futures_executor has been around for many years before pollster and provides things like thread pools that pollster does not provide.

You are free to extract code from futures under the appropriate license (there are many more than pollster), but they are all unofficial, not reviewed by futures maintainers, and there is no motivation on futures side to mention them.

**Comment by taiki-e** [comment]
> there is no motivation on futures side to mention them.

Also, even if there is a motivation, it is not always easy to mention a specific third-party crate from a crate that belongs to rust-lang or its project. If some over-passionate stakeholders feel that their project is being treated unfairly, they will try to "correct" it in various ways. Some of them can feel like spam or threats.
