### ISSUE TITLE
Memory leak with LocalFutureObj when not using Boxed futures

### ISSUE THREAD

**Issue by EricRnR** [rust-lang/futures-rs#2748]
When using LocalFutureObj directly, the drop on LocalFutureObj [here](https://github.com/rust-lang/futures-rs/blob/3b0378bbfde4bb0503acc412793f75c0a7708164/futures-task/src/future_obj.rs#L47) refers to the one of the empty drop function implementations such as [here](https://github.com/rust-lang/futures-rs/blob/3b0378bbfde4bb0503acc412793f75c0a7708164/futures-task/src/future_obj.rs#L202).  The future will never be dropped, unlike the Boxed counterparts.

**Comment by taiki-e** [comment]
cc @Nemo157

**Comment by Nemo157** [comment]
@EricRnR do you have a code example? The empty drop implementations are for borrowed instances, so they don't need to do anything, the owner will drop the values at some point after the `LocalFutureObj` stops borrowing them. Other owning types are expected to implement `UnsafeFutureObj` themselves like `Box` does.

**Comment by EricRnR** [comment]
Yes, this makes sense.  For some reason I had convinced myself UnsafeFutureObj was not part of the public API and I had no hook into the drop.  Crisis averted!
