### ISSUE TITLE
`TryFlattenUnordered` doesn't impl `TryStream`

### ISSUE THREAD

**Issue by tamird** [rust-lang/futures-rs#2796]
Should it? cc @olegnn @taiki-e ref. https://github.com/rust-lang/futures-rs/pull/2577

**Comment by taiki-e** [comment]
All streams has Result as Item automatically implements TryStream.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bcc661e8460203d89bb8810d602eaa39
