### ISSUE TITLE
Warn when PR is opened for 0.3/0.1 branch

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/futures-rs#2813]
This would help avoid problems like https://github.com/rust-lang/futures-rs/pull/2801#issuecomment-1819252187.

rust-lang/rust already has a mechanism for this (https://github.com/rust-lang/rust/pull/118607#issuecomment-1838839291), but I don't know how to enable it for this repo.

**Comment by edef1c** [comment]
I think having explicit mention of it in CONTRIBUTING.md would be a good start or even any documentation about the branching policy at all. I explicitly looked for some, didn't find any, found that HEAD pointed at 0.4, and figured I should target my bugfix to the release branch.

In other words, it wasn't exactly an accident: it was my genuine best guess at how to get a bugfix merged into a previous release line in the absence of documentation, given that I was uncertain that a fix to master would get cherry-picked to a release branch.

**Comment by taiki-e** [comment]
cc @Kobzol: Are there any options for doing this in rust-lang/team or somewhere?
I was going to refer to what rust-lang/rust does in rust-lang/team, but rust.toml doesn't seem to exist in the [dierctry that futures-rs.toml exist](https://github.com/rust-lang/team/tree/master/repos/rust-lang), so I'm not sure what to do.

**Comment by Kobzol** [comment]
Not in `rust-lang/team`, this is a functionality of rustbot/triagebot. Also, `rust-lang/rust` isn't managed by `team`, it will probably be the last repo to be added due to its complexity :laughing:

You need to configure [this](https://github.com/rust-lang/rust/blob/master/triagebot.toml#L646) in the [triagebot](https://github.com/rust-lang/futures-rs/blob/master/triagebot.toml) file.

**Comment by taiki-e** [comment]
> You need to configure [this](https://github.com/rust-lang/rust/blob/master/triagebot.toml#L646) in the [triagebot](https://github.com/rust-lang/futures-rs/blob/master/triagebot.toml) file.

Thanks! I opened a PR to enable it.
