### ISSUE TITLE
Different `waker_vtable` addresses for same type

### ISSUE THREAD

**Issue by timotheyca** [rust-lang/futures-rs#2864]
```rs
use futures::task::ArcWake;

struct Temp;

impl ArcWake for Temp {
    fn wake_by_ref(arc_self: &std::sync::Arc<Self>) {
        let _ = arc_self;
    }
}

fn main() {
    let temp = std::sync::Arc::new(Temp);
    let waker = futures::task::waker_ref(&temp);
    println!("{waker:?} {:?}", waker.clone());
    futures::executor::block_on(async {});
}
```

*Sometimes* (more often than not, in my experience), when running in `--release` mode, vtable addresses don't match:

```rs
WakerRef { waker: ManuallyDrop { value: Waker { data: 0x5654d35e5b90, vtable: 0x5654d2ad62b8 } }, _marker: PhantomData<&()> } Waker { data: 0x5654d35e5b90, vtable: 0x5654d2ad6308 }
```

Why this matters: this leads to `AtomicWaker` and alike to clone (or, worse, wake) on each poll because of how `Waker::will_wake` compares `Waker`s. Example: https://github.com/sdroege/async-tungstenite/issues/133

Is this a compiler bug? If yes, can we do something to mitigate it?

**Comment by taiki-e** [comment]
Same issue as https://github.com/rust-lang/futures-rs/pull/2829#issuecomment-1962863389 / https://github.com/rust-lang/rust/pull/121622#issuecomment-1975888092?

**Comment by timotheyca** [comment]
For the state of `futures-rs` crate, that I'm testing, all tests (including `task_arc_wake`) pass. `rustc` versions where I've seen the bug happen: 1.78, 1.79 and `rustc 1.80.0-nightly (36153f1a4 2024-05-24)`.

`codegen-units = 1` prevents the separation of addresses.

**Comment by timotheyca** [comment]
yes, seems to be the same issue

**Comment by timotheyca** [comment]
`#[inline(always)]` on `clone_arc_raw` has some positive effect on the situation (`ref_wake_same` passes)

**Comment by sdroege** [comment]
Quoting myself [from](https://github.com/sdroege/async-tungstenite/issues/133#issuecomment-2170082978)

> [...] this sounds like a bug in the code doing the comparison. If multiple codegen units are involved, it's not guaranteed that the vtable is always the same for the same object.
> 
> That's why e.g. https://doc.rust-lang.org/stable/std/sync/struct.Arc.html#method.ptr_eq exists.

**Comment by taiki-e** [comment]
Resolved by https://github.com/rust-lang/futures-rs/pull/2865
