### ISSUE TITLE
Typo in futures::io::SeeKRelative

### ISSUE THREAD

**Issue by belkadan** [rust-lang/futures-rs#2867]
The K is capitalized, but shouldn't be. (This is a public type, so take care in renaming it, I guess?)

**Comment by taiki-e** [comment]
already fixed. see https://github.com/rust-lang/futures-rs/pull/2603
> This is a public API, so I cannot backport this fix.

**Comment by belkadan** [comment]
Oops, I searched Issues and forgot to search PRs, sorry for the noise!

**Comment by belkadan** [comment]
I would think you could add a `type SeeKRelative<'a, R> = SeekRelative<'a, R>;` to backport though? Does that lose fidelity somewhere?

**Comment by taiki-e** [comment]
Type aliases seem to be a good idea.
