### ISSUE TITLE
Fails to build when any sanitizer is enabled

### ISSUE THREAD

**Issue by cmazakas** [rust-lang/futures-rs#2888]
I have a project where I'm using:
```toml
[dev-dependencies]
futures = { version = "0.3.30"}
```

In my tests, I'm using `FuturesOrdered` and `FuturesUnordered`.

When I run:
```bash
RUSTFLAGS="-Zsanitizer=thread" cargo +nightly test --test spawn
```

I see:
```
  Compiling futures-macro v0.3.30
   Compiling futures-util v0.3.30
error[E0463]: can't find crate for `futures_macro`
 --> /home/exbigboss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/async_await/stream_select_mod.rs:5:9
  |
5 | pub use futures_macro::stream_select_internal;
  |         ^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `futures_macro`
  --> /home/exbigboss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/async_await/join_mod.rs:84:9
   |
84 | pub use futures_macro::join_internal;
   |         ^^^^^^^^^^^^^ can't find crate
```

Not sure who/what is at fault here but I can work around the issue by using:
```toml
[dev-dependencies]
futures = { version = "0.3.30", default-features = false, features = ["alloc"] }
```

**Comment by taiki-e** [comment]
You need to pass `--target` option.

Documentation: https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#build-scripts-and-procedural-macros

> ## [Build scripts and procedural macros](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#build-scripts-and-procedural-macros)
> Use of sanitizers together with build scripts and procedural macros is technically possible, but in almost all cases it would be best avoided. This is especially true for procedural macros which would require an instrumented version of rustc.
>
> In more practical terms when using cargo always remember to pass --target flag, so that rustflags will not be applied to build scripts and procedural macros.

**Comment by cmazakas** [comment]
Hey, thank you so much!

```bash
RUSTFLAGS="-Zsanitizer=thread" cargo test --test spawn --target x86_64-unknown-linux-gnu
```
works perfectly for me!

Guess I should've RTFM'd lol. I appreciate your time.
