### ISSUE TITLE
futures-util-0.3.31 cannot be built with Rust 1.69

### ISSUE THREAD

**Issue by MageSlayer** [rust-lang/futures-rs#2893]
Hi

I am stuck (for various reasons) with rustc 1.69.0-nightly (31f858d9a 2023-02-28).

However futures-util-0.3.31 cannot be built with it.
See below.

```
error[E0658]: use of unstable library feature 'io_slice_advance'
  --> /home/denis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.31/src/io/write_all_vectored.rs:22:9
   |
22 |         IoSlice::advance_slices(&mut bufs, 0);
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #62726 <https://github.com/rust-lang/rust/issues/62726> for more information
   = help: add `#![feature(io_slice_advance)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'io_slice_advance'
  --> /home/denis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.31/src/io/write_all_vectored.rs:37:17
   |
37 |                 IoSlice::advance_slices(&mut this.bufs, n);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #62726 <https://github.com/rust-lang/rust/issues/62726> for more information
   = help: add `#![feature(io_slice_advance)]` to the crate attributes to enable

```

I guess you need to include #![feature(io_slice_advance)] and release next version.
Currently 0.3 branch has nothing besides 0.3.31 and is a real blocker.

BR

**Comment by taiki-e** [comment]
Also, when sticking with a particular older Rust, I strongly recommend that you commit the lockfile to prevent newer versions of dependencies from being automatically obtained.

This issue's case is a bit of a special case that depends on an unstable feature, but usually, in Rust ecosystem, increasing the minimum supported compiler version is not considered a breaking change.
