### ISSUE TITLE
Feature: Single-owner lock type

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/futures-rs#298]
While BiLock is quite useful for stream type, a traditional style lock is still useful.

**Comment by alexcrichton** [comment]
Certainly! This is only left out as it's not implemented yet. The `BiLock` type was immediately useful and easy to implement, which is basically the only reason it exists.

**Comment by taiki-e** [comment]
This has been implemented as `futures::lock::Mutex`.
